/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔历史回测：按收盘窗口顺序模拟随机方向 + 倍投，结果实时追加到 Excel。
 * 用法: npm run martingale-backtest（策略变量在 `.env.martingale`）
 * Generated By AI End (Cursor)
 */

import '../martingale/martingalePreamble';
import { martingaleConfigFromEnv } from '../martingale/martingaleConfig';
import { styleMartingaleConsoleBlock } from '../martingale/martingaleLogStyle';
import { runMartingaleBacktest } from '../martingale/martingaleBacktest';
import Logger from '../utils/logger';

const main = async () => {
    const cfg = martingaleConfigFromEnv();
    Logger.info(
        `马丁格尔回测开始 | 资产 ${cfg.assets.join(',')} | 周期 ${cfg.intervals.join(',')} | 回溯 ${cfg.backtestDays} 天 | 请求间隔 ${cfg.backtestRequestGapMs}ms | 输出 ${cfg.excelReportPath}`
    );
    const { rowsWritten, lines } = await runMartingaleBacktest(cfg);
    for (const ln of lines) {
        Logger.info(styleMartingaleConsoleBlock(ln));
    }
    Logger.success(`回测结束，累计写入 ${rowsWritten} 行`);
};

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
