/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔实盘：需 `MARTINGALE_LIVE_ENABLED=true`。
 * 可选 `MARTINGALE_LIVE_CONFIG_ISOLATED=true`：RPC/CLOB/Mongo/USDC/钱包等全部在 `.env.martingale` 的 `MARTINGALE_LIVE_*` 中配置，与根 `.env` 脱钩（见 `.env.martingale.example`）。
 * 用法: npm run martingale-live
 * Generated By AI End (Cursor)
 */

import '../martingale/martingalePreamble';
import connectDB from '../config/db';
import { ENV } from '../config/env';
import { martingaleConfigFromEnv } from '../martingale/martingaleConfig';
import { mulberry32 } from '../martingale/martingaleRng';
import { styleMartingaleConsoleBlock } from '../martingale/martingaleLogStyle';
import { applyMartingaleLiveRuntimeOverrides } from '../martingale/martingaleLiveEnv';
import { runMartingalePeriodicRedeem } from '../martingale/martingalePeriodicRedeem';
import { runMartingaleOnce } from '../martingale/martingaleRunner';
import createClobClient from '../utils/createClobClient';
import { performHealthCheck, logHealthCheck } from '../utils/healthCheck';
import Logger from '../utils/logger';
import { isRetryableTransientError, transientBackoffMs, sleep } from '../utils/transientErrors';

const loopSleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** 与 Logger 一致的地址脱敏，仅用于启动摘要 */
const maskWalletForLog = (addr: string): string => {
    const a = (addr || '').trim();
    if (a.length <= 12) {
        return a || '—';
    }
    return `${a.slice(0, 6)}…${a.slice(-4)}`;
};

/** 库表连接 + 健康检查 + 钱包/CLOB 摘要；隔离且无 MARTINGALE_LIVE_MONGO_URI 时跳过 Mongo */
const runMartingaleLiveStartupChecks = async (): Promise<void> => {
    const skipMongo = process.env.MARTINGALE_LIVE_SKIP_MONGO === 'true';
    if (skipMongo) {
        Logger.warning('马丁实盘：未配置 Mongo（MARTINGALE_LIVE_MONGO_URI），已跳过数据库连接；健康检查中数据库项将标为已跳过。');
    } else {
        await connectDB();
    }
    Logger.separator();
    Logger.header('马丁格尔实盘 · 环境与钱包');
    Logger.info(`交易钱包 PROXY_WALLET: ${maskWalletForLog(ENV.PROXY_WALLET)}`);
    Logger.info(`CLOB HTTP: ${ENV.CLOB_HTTP_URL}`);
    Logger.info(`RPC: ${ENV.RPC_URL}`);
    if (ENV.HTTP_PROXY_ENABLED) {
        Logger.info(`HTTP 代理: ${ENV.HTTP_PROXY_HOST}:${ENV.HTTP_PROXY_PORT}`);
    } else {
        Logger.info('HTTP 代理: 未启用');
    }
    Logger.info('正在执行健康检查（与 npm start 同源：库 / RPC / 余额 / Polymarket API）…');
    const healthResult = await performHealthCheck();
    logHealthCheck(healthResult);
    if (!healthResult.healthy) {
        Logger.warning('健康检查未完全通过，马丁实盘仍将尝试继续（请尽快修复标红项）。');
    }
    Logger.separator();
};

const createClobWithRetry = async () => {
    let streak = 0;
    const maxAttempts = ENV.CLOB_INIT_MAX_ATTEMPTS;
    while (true) {
        try {
            return await createClobClient();
        } catch (e) {
            streak += 1;
            if (!isRetryableTransientError(e) || streak >= maxAttempts) {
                throw e;
            }
            const delayMs = transientBackoffMs(streak);
            Logger.warning(
                `CLOB 初始化失败，约 ${(delayMs / 1000).toFixed(1)}s 后重试（第 ${streak}/${maxAttempts} 次）: ${e}`
            );
            await sleep(delayMs);
        }
    }
};

const main = async () => {
    const cfg = martingaleConfigFromEnv();
    if (!cfg.liveEnabled) {
        Logger.warning('MARTINGALE_LIVE_ENABLED 未为 true，退出。请在 .env.martingale 中开启。');
        process.exit(0);
    }
    const envOv = applyMartingaleLiveRuntimeOverrides();
    if (envOv.isolated) {
        Logger.warning(
            '马丁实盘：已启用 MARTINGALE_LIVE_CONFIG_ISOLATED，链/CLOB/库/钱包等以 .env.martingale 中 MARTINGALE_LIVE_* 为准（已注入本进程 ENV）。'
        );
    } else if (envOv.appliedSummary.length > 0) {
        Logger.info(`马丁实盘：已从 .env.martingale 覆盖 → ${envOv.appliedSummary.join(', ')}（仅本进程）`);
    }
    await runMartingaleLiveStartupChecks();
    const statePathLive =
        cfg.liveStateFilePath && cfg.liveStateFilePath.trim() !== ''
            ? cfg.liveStateFilePath.trim()
            : cfg.stateFilePath;
    const cfgLive = { ...cfg, stateFilePath: statePathLive };
    const seed = cfg.randomSeed ?? Math.floor(Math.random() * 0x7fffffff);
    const rng = mulberry32(seed);
    Logger.info(
        `马丁格尔实盘启动 | seed=${seed} | 选边=${cfg.entrySideMode === 'trend_follow' ? `趋势(偏高≥${cfg.trendFollowMinLeadingPrice}${cfg.trendFollowMinSpread > 0 ? ` 价差≥${cfg.trendFollowMinSpread}` : ''})` : '随机'} | 常规轮询 ${cfg.pollIntervalSec}s | 临收盘加速≤${cfg.pollIntervalNearCloseSec}s(阈值${cfg.nearClosePollThresholdSec}s) | 本轮若结算则立刻连扫第二轮再接休眠 | Gamma HTTP 超时=${cfg.httpTimeoutMs}ms 重试=${cfg.httpRetryLimit}次 | 单行待收盘心跳≥${cfg.pendingCountdownLogSec}s | 逾期推断宽限=${cfg.forceSettleGraceAfterWindowSec}s | 订单簿快速结算延迟=${cfg.bookSettleAfterWindowSec}s(价差≥${cfg.bookSettleMinSpread}) | 定期赎回=${cfg.redeemIntervalMinutes > 0 ? `每${cfg.redeemIntervalMinutes}分` : '关'} | 启动等下一窗=${cfg.startupWaitNextWindow ? '开' : '关'}(首单窗内宽限≤${cfg.startupCurrentWindowGraceSec}s) | 邮件下单=${cfg.emailOnOrder ? '开' : '关'} 结算=${cfg.emailOnSettle ? '开' : '关'}(须根.env EMAIL_NOTIFY) | 状态JSON=${statePathLive}${cfg.liveStateFilePath ? '(LIVE专用)' : ''} | Excel=${cfg.excelReportPath} | ⚠️ 将下真实订单`
    );
    Logger.info(
        `参与资产: ${cfg.assets.join(',')} | 参与周期: ${cfg.intervals.join(',')} | 环境串 MARTINGALE_INTERVALS=${JSON.stringify((process.env.MARTINGALE_INTERVALS || '').trim())}`
    );
    Logger.info(
        '说明: 马丁档位按 state 键「资产:周期」独立（如 BTC:5m 与 ETH:5m 各一条链）；与日志前缀 [BTC:5m] 一致。'
    );
    Logger.info('正在初始化 CLOB 客户端（实盘签名下单）…');
    const clob = await createClobWithRetry();
    Logger.success('CLOB 客户端就绪，进入马丁轮询');
    let n = 0;
    let lastMartingaleRedeemAt = 0;
    while (true) {
        n += 1;
        try {
            const first = await runMartingaleOnce(cfgLive, rng, { execution: 'live', clob });
            let linesOut = first.lines;
            let sleepSec = first.nextSleepSec;
            if (first.settledThisPass) {
                const second = await runMartingaleOnce(cfgLive, rng, { execution: 'live', clob });
                linesOut = first.lines.concat(second.lines);
                sleepSec = Math.min(first.nextSleepSec, second.nextSleepSec);
            }
            for (const ln of linesOut) {
                Logger.info(styleMartingaleConsoleBlock(ln));
            }
            if (cfgLive.redeemIntervalMinutes > 0) {
                const gapMs = cfgLive.redeemIntervalMinutes * 60_000;
                if (Date.now() - lastMartingaleRedeemAt >= gapMs) {
                    lastMartingaleRedeemAt = Date.now();
                    try {
                        await runMartingalePeriodicRedeem();
                    } catch (redeemErr) {
                        Logger.warning(
                            `[马丁·定期赎回] 本轮异常: ${redeemErr instanceof Error ? redeemErr.message : String(redeemErr)}`
                        );
                    }
                }
            }
            await loopSleep(sleepSec * 1000);
        } catch (e) {
            Logger.error(`第 ${n} 轮扫描失败: ${e}`);
            await loopSleep(cfgLive.pollIntervalSec * 1000);
        }
    }
};

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
