/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔模拟盘：轮询 Gamma slug，随机选边，结算后追加 Excel（不调用 CLOB 实盘下单）。
 * 用法: npm run martingale-dryrun（策略变量在 `.env.martingale`）
 * Generated By AI End (Cursor)
 */

import * as fs from 'fs';
import * as path from 'path';
import '../martingale/martingalePreamble';
import { martingaleConfigFromEnv } from '../martingale/martingaleConfig';
import { mulberry32 } from '../martingale/martingaleRng';
import { styleMartingaleConsoleBlock } from '../martingale/martingaleLogStyle';
import { resetMartingaleRunnerSessionCaches, runMartingaleOnce } from '../martingale/martingaleRunner';
import Logger from '../utils/logger';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const main = async () => {
    const cfg = martingaleConfigFromEnv();
    if (!cfg.enabled) {
        Logger.warning('MARTINGALE_ENABLED 未为 true，退出。请在 `.env.martingale` 中开启（示例见 `.env.martingale.example`）。');
        process.exit(0);
    }
    if (cfg.dryRunResetStateOnStart) {
        const abs = path.resolve(cfg.stateFilePath);
        resetMartingaleRunnerSessionCaches();
        if (fs.existsSync(abs)) {
            fs.unlinkSync(abs);
            Logger.warning(`已按 MARTINGALE_DRYRUN_RESET_STATE_ON_START 删除状态文件（各序列从首笔重来）: ${abs}`);
        } else {
            Logger.info(`MARTINGALE_DRYRUN_RESET_STATE_ON_START 已开启，状态文件尚不存在: ${abs}`);
        }
    } else {
        Logger.info(
            `提示: BTC/ETH 等步数与金额来自独立 state 键，持久化在 ${cfg.stateFilePath}；与「刚开终端」无关。若要本次全员从首笔 1× 重来，请设 MARTINGALE_DRYRUN_RESET_STATE_ON_START=true 或手动删该 JSON。`
        );
    }
    const seed = cfg.randomSeed ?? Math.floor(Math.random() * 0x7fffffff);
    const rng = mulberry32(seed);
    const pollSec = cfg.dryRunPollIntervalSec ?? cfg.pollIntervalSec;
    Logger.info(
        `马丁格尔模拟盘启动 | seed=${seed} | 选边=${cfg.entrySideMode === 'trend_follow' ? `趋势(偏高≥${cfg.trendFollowMinLeadingPrice}${cfg.trendFollowMinSpread > 0 ? ` 价差≥${cfg.trendFollowMinSpread}` : ''})` : '随机'} | 常规轮询 ${pollSec}s | 临收盘加速≤${cfg.pollIntervalNearCloseSec}s(理论窗已过/rem<0/距end<${cfg.nearClosePollThresholdSec}s/拉盘失败) | 本轮若结算则立刻连扫第二轮再接休眠 | Gamma HTTP 超时=${cfg.httpTimeoutMs}ms 重试=${cfg.httpRetryLimit}次 | 基础金额 ${(cfg.dryRunBaseStakeUsd ?? cfg.baseStakeUsd).toFixed(4)} USD | 单行待收盘心跳≥${cfg.pendingCountdownLogSec}s | 逾期推断宽限=${cfg.forceSettleGraceAfterWindowSec}s | 详情日志=${cfg.logVerbose ? '开' : '关'} | 启动等下一窗=${cfg.startupWaitNextWindow ? '开' : '关'}(首单窗内宽限≤${cfg.startupCurrentWindowGraceSec}s) | 邮件下单=${cfg.emailOnOrder ? '开' : '关'} 结算=${cfg.emailOnSettle ? '开' : '关'} 押边≠偏高=${cfg.emailOnTrendMismatch ? '开' : '关'}(须根.env EMAIL_NOTIFY) | Excel=${cfg.excelReportPath}`
    );
    Logger.info(
        `参与资产: ${cfg.assets.join(',')} | 参与周期: ${cfg.intervals.join(',')}（须与日志前缀 [BTC:5m] 一致）| 环境串 MARTINGALE_INTERVALS=${JSON.stringify((process.env.MARTINGALE_INTERVALS || '').trim())}`
    );
    if (!cfg.logVerbose) {
        Logger.info(
            '说明: 默认单行日志；挂单=closed 后才会开下一盘。要恢复长说明块请设 MARTINGALE_LOG_VERBOSE=true'
        );
        Logger.info(
            '说明: 马丁档位按 state 键「资产:周期」独立（如 BTC:5m 与 ETH:5m 各算一条链）；日志里「本序列档」仅对应该键。'
        );
    }
    let n = 0;
    while (true) {
        n += 1;
        try {
            const first = await runMartingaleOnce(cfg, rng);
            let linesOut = first.lines;
            let sleepSec = first.nextSleepSec;
            if (first.settledThisPass) {
                const second = await runMartingaleOnce(cfg, rng);
                linesOut = first.lines.concat(second.lines);
                sleepSec = Math.min(first.nextSleepSec, second.nextSleepSec);
            }
            for (const ln of linesOut) {
                Logger.info(styleMartingaleConsoleBlock(ln));
            }
            await sleep(sleepSec * 1000);
        } catch (e) {
            Logger.error(`第 ${n} 轮扫描失败: ${e}`);
            await sleep(pollSec * 1000);
        }
    }
};

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
