/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔：每笔结算后追加一行到 Excel（exceljs）；表头为「中文 (英文键)」。
 * Generated By AI End (Cursor)
 */

import * as fs from 'fs';
import * as path from 'path';
import ExcelJS from 'exceljs';

export type MartingaleExcelRow = {
    timeUtc: string;
    asset: string;
    interval: string;
    slug: string;
    windowStartUtc: string;
    sidePicked: string;
    winningOutcome: string;
    stakeUsd: string;
    stepIndex: string;
    won: string;
    pnlRoundUsd: string;
    cumulativeLossBeforeUsd: string;
    stepAfter: string;
    conditionId: string;
    tokenId: string;
    assumedShares: string;
    execPrice: string;
    execMode: string;
    discovery: string;
    notes: string;
};

const SHEET = 'martingale';

const COLUMN_ORDER: { key: keyof MartingaleExcelRow; headerZh: string }[] = [
    { key: 'timeUtc', headerZh: '记录时间' },
    { key: 'asset', headerZh: '资产' },
    { key: 'interval', headerZh: '周期' },
    { key: 'slug', headerZh: '市场 slug' },
    { key: 'windowStartUtc', headerZh: '窗口起点(UTC)' },
    { key: 'sidePicked', headerZh: '下注方向' },
    { key: 'winningOutcome', headerZh: '胜出结果' },
    { key: 'stakeUsd', headerZh: '名义本金(USD)' },
    { key: 'stepIndex', headerZh: '结算前马丁步' },
    { key: 'won', headerZh: '是否猜中' },
    { key: 'pnlRoundUsd', headerZh: '本局盈亏(USD)' },
    { key: 'cumulativeLossBeforeUsd', headerZh: '结算前累计亏损(USD)' },
    { key: 'stepAfter', headerZh: '结算后马丁步' },
    { key: 'conditionId', headerZh: '条件 ID' },
    { key: 'tokenId', headerZh: 'CLOB 代币 ID' },
    { key: 'assumedShares', headerZh: '份额(假设或成交)' },
    { key: 'execPrice', headerZh: '价格(参考或成交)' },
    { key: 'execMode', headerZh: '模式' },
    { key: 'discovery', headerZh: '发现方式' },
    { key: 'notes', headerZh: '备注' },
];

const headerTitles = (): string[] =>
    COLUMN_ORDER.map((c) => `${c.headerZh} (${c.key})`);

export const appendMartingaleExcelRow = async (
    filePath: string,
    row: MartingaleExcelRow
): Promise<void> => {
    const abs = path.resolve(filePath);
    const dir = path.dirname(abs);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    const wb = new ExcelJS.Workbook();
    if (fs.existsSync(abs)) {
        await wb.xlsx.readFile(abs);
    }
    let ws = wb.getWorksheet(SHEET);
    if (!ws) {
        ws = wb.addWorksheet(SHEET);
        ws.addRow(headerTitles());
    }
    const values = COLUMN_ORDER.map((c) => row[c.key]);
    ws.addRow(values);
    await wb.xlsx.writeFile(abs);
};
