/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔序列结算与步进（模拟 / 回测 / 实盘共用）。
 * Generated By AI End (Cursor)
 */

import { roundPnlUsd } from './martingalePnl';
import type { MartingaleRuntimeConfig } from './martingaleConfig';
import type { MartingaleSeriesPersisted } from './martingaleState';

export type SettlementOutcome = {
    pnlUsd: number;
    stepBefore: number;
    stepAfter: number;
    cumulativeLossBeforeUsd: number;
    cumulativeLossAfterUsd: number;
    note: string;
};

export const applyOutcomeToSeries = (
    series: MartingaleSeriesPersisted,
    cfg: MartingaleRuntimeConfig,
    won: boolean,
    stakeUsd: number,
    entryPrice: number
): SettlementOutcome => {
    const stepBefore = series.stepIndex;
    const cumBefore = series.cumulativeLossUsdInSeries;
    const pnlUsd = roundPnlUsd(stakeUsd, entryPrice, won);
    let note = won ? 'win_reset' : 'loss_continue_or_reset';
    if (won) {
        series.stepIndex = 0;
        series.cumulativeLossUsdInSeries = 0;
    } else {
        const lostStake = -Math.min(0, pnlUsd);
        series.cumulativeLossUsdInSeries += lostStake;
        if (series.stepIndex >= cfg.maxMartingaleSteps - 1) {
            series.stepIndex = 0;
            series.cumulativeLossUsdInSeries = 0;
            note = 'loss_max_steps_reset';
        } else {
            series.stepIndex += 1;
        }
    }
    return {
        pnlUsd,
        stepBefore,
        stepAfter: series.stepIndex,
        cumulativeLossBeforeUsd: cumBefore,
        cumulativeLossAfterUsd: series.cumulativeLossUsdInSeries,
        note,
    };
};
