/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔脚本入口须**作为第一条 import**：先合并 .env，再置位以抑制跟单启动摘要（避免误显「正买/反买」）。
 * Generated By AI End (Cursor)
 */

import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(process.cwd(), '.env.martingale'), override: true });
process.env.MARTINGALE_SUPPRESS_COPY_LOG = 'true';
