/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * Polymarket 网页链接与可读时间文案（控制台日志用）。
 * Generated By AI End (Cursor)
 */

import type { GammaMarketLite } from './martingaleMarket';
import { remainingSecondsUntilEnd } from './martingaleMarket';

/**
 * 短时 Up/Down 在 polymarket.com 上应以 /event/{slug} 打开，与 5m/15m 聚合页一致；
 * 使用 /market/{slug} 时站点常展示为更长周期视图，易与真实粒度混淆。
 */
export const polymarketMarketPageUrl = (slug: string): string => {
    const s = slug.trim();
    return `https://polymarket.com/event/${encodeURIComponent(s)}`;
};

const martingaleTerminalHyperlinkEnabled = (): boolean => {
    if (process.env.MARTINGALE_TERMINAL_HYPERLINK === 'false') {
        return false;
    }
    if (process.env.CI === 'true') {
        return false;
    }
    if (process.stdout.isTTY !== true) {
        return false;
    }
    return true;
};

/**
 * OSC 8 终端超链接（VS Code / Windows Terminal / iTerm2 等可 Ctrl+点击）；非 TTY 或 CI 时退回纯文本。
 */
export const terminalOsc8Hyperlink = (url: string, visibleText: string): string => {
    const u = url.trim();
    const t = (visibleText || u).trim();
    if (!u.startsWith('http') || !martingaleTerminalHyperlinkEnabled()) {
        return t;
    }
    return `\u001b]8;;${u}\u001b\\${t}\u001b]8;;\u001b\\`;
};

/** 马丁控制台日志用：slug → 可点击盘口链（写文件前需 stripOsc8） */
export const martingaleConsoleMarketUrl = (slug: string): string => {
    const plain = polymarketMarketPageUrl(slug);
    return terminalOsc8Hyperlink(plain, plain);
};

export const formatRemainingUntilEndZh = (m: GammaMarketLite): string => {
    const r = remainingSecondsUntilEnd(m);
    if (r === null) {
        return '未知（Gamma 未返回 endDate）';
    }
    if (r < 0) {
        return '已过期';
    }
    const mm = Math.floor(r / 60);
    const ss = Math.floor(r % 60);
    if (mm >= 60) {
        const hh = Math.floor(mm / 60);
        const m2 = mm % 60;
        return `约 ${hh} 小时 ${m2} 分`;
    }
    return `约 ${mm} 分 ${ss} 秒`;
};

/**
 * 距 Gamma endDate 的显式数字倒计时（便于控制台每 N 秒刷新对照）。
 */
export const formatCountdownClockZh = (m: GammaMarketLite): string => {
    const r = remainingSecondsUntilEnd(m);
    if (r === null) {
        return 'n/a';
    }
    if (r < 0) {
        return '00:00(已过期)';
    }
    const total = Math.floor(r);
    const hh = Math.floor(total / 3600);
    const mm = Math.floor((total % 3600) / 60);
    const ss = total % 60;
    if (hh > 0) {
        return `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}:${String(ss).padStart(2, '0')}`;
    }
    return `${String(mm).padStart(2, '0')}:${String(ss).padStart(2, '0')}`;
};

export const shortConditionId = (cid: string, head = 10, tail = 6): string => {
    const t = cid.trim();
    if (t.length <= head + tail + 3) {
        return t || '—';
    }
    return `${t.slice(0, head)}…${t.slice(-tail)}`;
};

export const shortTokenId = (tid: string, head = 12, tail = 8): string => {
    const t = tid.trim();
    if (t.length <= head + tail + 3) {
        return t || '—';
    }
    return `${t.slice(0, head)}…${t.slice(-tail)}`;
};
