/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * Polymarket Gamma：短时加密 Up/Down 市场 slug 解析与胜负判定（供马丁格尔模拟/回测使用）。
 * Generated By AI End (Cursor)
 */

import axios from 'axios';
import fetchData, { type FetchDataOptions } from '../utils/fetchData';

export type GammaMarketLite = {
    slug?: string;
    conditionId?: string;
    question?: string;
    closed?: boolean;
    outcomes?: string | string[];
    outcomePrices?: string | number[];
    clobTokenIds?: string | string[];
    endDate?: string;
    active?: boolean;
};

const GAMMA_SLUG_BASE = 'https://gamma-api.polymarket.com/markets/slug';

export const floorToWindowStart = (nowSec: number, intervalSec: number): number => {
    return Math.floor(nowSec / intervalSec) * intervalSec;
};

export const buildUpdownSlug = (assetSlugPrefix: string, intervalLabel: string, windowStartSec: number): string => {
    const p = assetSlugPrefix.trim().toLowerCase();
    const lab = intervalLabel.trim().toLowerCase();
    return `${p}-updown-${lab}-${windowStartSec}`;
};

export const parseJsonArrayField = (raw: unknown): string[] => {
    if (Array.isArray(raw)) {
        return raw.map((x) => String(x));
    }
    if (typeof raw === 'string') {
        try {
            const j = JSON.parse(raw) as unknown;
            return Array.isArray(j) ? j.map((x) => String(x)) : [];
        } catch {
            return [];
        }
    }
    return [];
};

export const parseOutcomePrices = (raw: unknown): number[] => {
    if (Array.isArray(raw)) {
        return raw.map((x) => Number(x)).filter((n) => !Number.isNaN(n));
    }
    if (typeof raw === 'string') {
        try {
            const j = JSON.parse(raw) as unknown;
            if (Array.isArray(j)) {
                return j.map((x) => Number(x)).filter((n) => !Number.isNaN(n));
            }
        } catch {
            return [];
        }
    }
    return [];
};

export const winningOutcomeIndex = (m: GammaMarketLite): number | null => {
    const prices = parseOutcomePrices(m.outcomePrices);
    if (prices.length < 2) {
        return null;
    }
    let best = 0;
    for (let i = 1; i < prices.length; i++) {
        if (prices[i] > prices[best]) {
            best = i;
        }
    }
    if (prices[best] >= 0.95) {
        return best;
    }
    return null;
};

/**
 * Gamma 仍标开放但 outcomePrices 已极度倾斜时，用于「逾期宽限期后强制结算」推断胜负（阈值低于 winningOutcomeIndex）。
 */
export const provisionalWinnerFromGammaPrices = (m: GammaMarketLite): number | null => {
    const prices = parseOutcomePrices(m.outcomePrices);
    if (prices.length < 2) {
        return null;
    }
    const a = prices[0];
    const b = prices[1];
    if (!Number.isFinite(a) || !Number.isFinite(b)) {
        return null;
    }
    if (a >= 0.88 && b <= 0.12) {
        return 0;
    }
    if (b >= 0.88 && a <= 0.12) {
        return 1;
    }
    if (a >= 0.93 && a > b) {
        return 0;
    }
    if (b >= 0.93 && b > a) {
        return 1;
    }
    return null;
};

export const fetchMarketBySlug = async (
    slug: string,
    http?: FetchDataOptions
): Promise<GammaMarketLite | null> => {
    const url = `${GAMMA_SLUG_BASE}/${encodeURIComponent(slug)}`;
    try {
        const data = (await fetchData(url, http)) as GammaMarketLite;
        if (!data || typeof data !== 'object') {
            return null;
        }
        return data;
    } catch (e) {
        if (axios.isAxiosError(e) && e.response?.status === 404) {
            return null;
        }
        throw e;
    }
};

/**
 * 用 Gamma endDate 与 slug 窗起点推算窗口长度（秒）。用于发现阶段剔除「slug 写 5m 但实际约 15m」等错配。
 */
export const gammaWindowDurationSec = (m: GammaMarketLite, windowStartSec: number): number | null => {
    const raw = m.endDate;
    if (raw == null || raw === '') {
        return null;
    }
    const endMs = typeof raw === 'string' ? Date.parse(raw) : NaN;
    if (!Number.isFinite(endMs)) {
        return null;
    }
    const startMs = windowStartSec * 1000;
    const d = (endMs - startMs) / 1000;
    if (!Number.isFinite(d) || d <= 0) {
        return null;
    }
    return d;
};

export const remainingSecondsUntilEnd = (m: GammaMarketLite): number | null => {
    const raw = m.endDate;
    if (raw == null || raw === '') {
        return null;
    }
    const ms = typeof raw === 'string' ? Date.parse(raw) : NaN;
    if (!Number.isFinite(ms)) {
        return null;
    }
    return (ms - Date.now()) / 1000;
};

export const isMarketTooCloseToExpiry = (m: GammaMarketLite, minRemainingSec: number): boolean => {
    if (minRemainingSec <= 0) {
        return false;
    }
    const r = remainingSecondsUntilEnd(m);
    if (r === null) {
        return false;
    }
    return r < minRemainingSec;
};

export const parseClobTokenIds = (m: GammaMarketLite): string[] => {
    const raw = m.clobTokenIds;
    if (Array.isArray(raw)) {
        return raw.map((x) => String(x).trim()).filter(Boolean);
    }
    if (typeof raw === 'string') {
        try {
            const j = JSON.parse(raw) as unknown;
            if (Array.isArray(j)) {
                return j.map((x) => String(x).trim()).filter(Boolean);
            }
        } catch {
            return [];
        }
    }
    return [];
};
