/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔脚本专用的环境变量加载顺序：
 * 1）加载项目根目录 `.env`（跟单机器人共用：钱包、CLOB、Mongo、代理等）
 * 2）再加载 `.env.martingale`（仅马丁格尔策略参数；若键名重复，以后者为准）
 * 这样跟单与马丁格尔配置分文件存放，避免一个 `.env` 里又跟单又马丁格尔混在一起。
 * Generated By AI End (Cursor)
 */

import * as dotenv from 'dotenv';
import * as path from 'path';

let martingaleDotenvMerged = false;

export const ensureMartingaleDotenv = (): void => {
    if (martingaleDotenvMerged) {
        return;
    }
    dotenv.config({ path: path.resolve(process.cwd(), '.env') });
    dotenv.config({ path: path.resolve(process.cwd(), '.env.martingale'), override: true });
    martingaleDotenvMerged = true;
};
