/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 二元仓位在固定入场价假设下的盈亏（模拟/回测；非链上精确结算）。
 * Generated By AI End (Cursor)
 */

import type { GammaMarketLite } from './martingaleMarket';
import { parseOutcomePrices } from './martingaleMarket';
import type { OpenMartingaleBet } from './martingaleState';

export const markToMarketUnrealizedUsd = (
    m: GammaMarketLite,
    ob: OpenMartingaleBet
): number | null => {
    const prices = parseOutcomePrices(m.outcomePrices);
    const idx = ob.sideIndex;
    if (idx < 0 || idx >= prices.length) {
        return null;
    }
    const mark = prices[idx];
    if (!Number.isFinite(mark)) {
        return null;
    }
    const entry = ob.entryPriceUsed;
    if (entry == null || !Number.isFinite(entry) || entry <= 0) {
        return null;
    }
    const shares = ob.assumedShares ?? ob.stakeUsd / entry;
    if (!Number.isFinite(shares)) {
        return null;
    }
    return shares * mark - ob.stakeUsd;
};

export const roundPnlUsd = (
    stakeUsd: number,
    entryPrice: number,
    won: boolean
): number => {
    const p = Math.min(0.99, Math.max(0.01, entryPrice));
    if (!won) {
        return -stakeUsd;
    }
    const shares = stakeUsd / p;
    return shares - stakeUsd;
};
