/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔实盘：CLOB FOK 市价买（与 postOrder 买入逻辑对齐的最小实现）。
 * Generated By AI End (Cursor)
 */

import { ClobClient, OrderType, Side } from '@polymarket/clob-client';
import { ENV } from '../config/env';
import Logger from '../utils/logger';

const MIN_ORDER_USD = 1.0;

type OrderBookEntry = { price: string; size: string };

const asksLen = (book: { asks?: OrderBookEntry[] }): number => {
    return Array.isArray(book.asks) ? book.asks.length : 0;
};

export type MartingaleBuyResult =
    | {
          ok: true;
          usdcSpent: number;
          execPrice: number;
          shares: number;
          tokenId: string;
      }
    | { ok: false; reason: string };

export const martingaleMarketBuyUsd = async (
    clob: ClobClient,
    tokenId: string,
    targetUsd: number
): Promise<MartingaleBuyResult> => {
    if (targetUsd < MIN_ORDER_USD) {
        return { ok: false, reason: `目标金额 $${targetUsd.toFixed(2)} 低于最小 $${MIN_ORDER_USD}` };
    }
    Logger.info(
        `[martingale-live] 开始买单 | token=${tokenId.slice(0, 14)}…${tokenId.slice(-6)} | 目标名义 $${targetUsd.toFixed(4)} | FOK 吃卖一`
    );
    let remaining = targetUsd;
    let totalShares = 0;
    let totalSpent = 0;
    let lastPrice = 0;
    let retry = 0;
    while (remaining >= MIN_ORDER_USD && retry < ENV.RETRY_LIMIT) {
        let orderBook: { asks?: OrderBookEntry[] };
        try {
            orderBook = await clob.getOrderBook(tokenId);
        } catch (e) {
            retry += 1;
            Logger.warning(`马丁格尔: 订单簿失败 (${retry}/${ENV.RETRY_LIMIT}): ${e}`);
            continue;
        }
        if (!asksLen(orderBook)) {
            return { ok: false, reason: '订单簿无卖单' };
        }
        const asks = orderBook.asks as OrderBookEntry[];
        const minPriceAsk = asks.reduce(
            (min: OrderBookEntry, ask: OrderBookEntry) =>
                parseFloat(ask.price) < parseFloat(min.price) ? ask : min,
            asks[0]
        );
        const rawAskPx = parseFloat(minPriceAsk.price);
        if (!Number.isFinite(rawAskPx) || rawAskPx < 0.01 || rawAskPx > 0.99) {
            return { ok: false, reason: `卖价异常: ${minPriceAsk.price}` };
        }
        const maxOrderUsd = parseFloat(minPriceAsk.size) * rawAskPx;
        const orderUsd = Math.min(remaining, maxOrderUsd);
        if (orderUsd < MIN_ORDER_USD) {
            return { ok: false, reason: `盘口深度不足 $${MIN_ORDER_USD}，当前可成交约 $${orderUsd.toFixed(2)}` };
        }
        const orderArgs = {
            side: Side.BUY,
            tokenID: tokenId,
            amount: orderUsd,
            price: rawAskPx,
        };
        try {
            const signed = await clob.createMarketOrder(orderArgs);
            const resp = await clob.postOrder(signed, OrderType.FOK);
            if (resp.success === true) {
                const bought = orderArgs.amount / orderArgs.price;
                totalShares += bought;
                totalSpent += orderArgs.amount;
                lastPrice = orderArgs.price;
                remaining -= orderArgs.amount;
                retry = 0;
                Logger.info(
                    `[martingale-live] FOK 成交一笔 | $${orderArgs.amount.toFixed(4)} @ ${orderArgs.price} | +${bought.toFixed(4)} 份 | 剩余目标 $${remaining.toFixed(4)}`
                );
            } else {
                retry += 1;
                const r = resp as { errorMsg?: string };
                const msg = typeof r.errorMsg === 'string' ? r.errorMsg : JSON.stringify(resp);
                Logger.warning(`马丁格尔: 下单失败 (${retry}/${ENV.RETRY_LIMIT}) ${msg}`);
            }
        } catch (e) {
            retry += 1;
            Logger.warning(`马丁格尔: 下单异常 (${retry}/${ENV.RETRY_LIMIT}): ${e}`);
        }
    }
    if (totalShares <= 0 || totalSpent <= 0) {
        Logger.warning(`[martingale-live] 买单未成交任何份额 | token=${tokenId.slice(0, 12)}…`);
        return { ok: false, reason: '未能成交任何份额' };
    }
    const avgPx = totalSpent / totalShares;
    Logger.info(
        `[martingale-live] 买单完成 | 总花费 $${totalSpent.toFixed(4)} | 加权均价 ${avgPx.toFixed(4)} | 总份额 ${totalShares.toFixed(4)}`
    );
    return {
        ok: true,
        usdcSpent: totalSpent,
        execPrice: avgPx,
        shares: totalShares,
        tokenId,
    };
};
