/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔：按「资产+周期」维度的序列状态持久化（JSON）。
 * Generated By AI End (Cursor)
 */

import * as fs from 'fs';
import * as path from 'path';
import type { MartingaleAsset, MartingaleIntervalKey, MartingaleRuntimeConfig } from './martingaleConfig';
import { seriesKey } from './martingaleConfig';

export type MartingaleExecMode = 'dryrun' | 'live' | 'backtest';

export type OpenMartingaleBet = {
    slug: string;
    windowStartSec: number;
    sideIndex: number;
    sideLabel: string;
    stakeUsd: number;
    conditionId: string;
    placedAtIso: string;
    tokenId?: string;
    entryPriceUsed?: number;
    assumedShares?: number;
    execMode?: MartingaleExecMode;
    discovery?: 'slug' | 'gamma_list';
};

export type MartingaleSeriesPersisted = {
    stepIndex: number;
    cumulativeLossUsdInSeries: number;
    /** 本进程内该序列已结算盈亏累计（USD，模拟/实盘均更新；仅内存+state 文件持久化） */
    sessionRealizedPnlUsd: number;
    /**
     * 趋势马丁专用：连输尚未重置时，累计「若各笔按当时入场价胜出则应赎回的美元」Σ(stakeUsd/entryPrice)。
     * 下一笔在隐含价 p 处，使单次胜能覆盖历史缺口的最小名义约为 T×p/(1−p)（与 0.5 入场时倍投 2^n 同构的推广）。
     */
    trendMartingaleRedeemTargetUsd?: number;
    openBet: OpenMartingaleBet | null;
};

export type MartingaleStateFile = {
    version: 1;
    updatedAt: string;
    series: Record<string, MartingaleSeriesPersisted>;
};

const emptySeries = (): MartingaleSeriesPersisted => ({
    stepIndex: 0,
    cumulativeLossUsdInSeries: 0,
    sessionRealizedPnlUsd: 0,
    trendMartingaleRedeemTargetUsd: 0,
    openBet: null,
});

export const loadMartingaleState = (filePath: string): MartingaleStateFile => {
    const abs = path.resolve(filePath);
    if (!fs.existsSync(abs)) {
        return { version: 1, updatedAt: new Date().toISOString(), series: {} };
    }
    try {
        const raw = fs.readFileSync(abs, 'utf8');
        const j = JSON.parse(raw) as MartingaleStateFile;
        if (!j || j.version !== 1 || typeof j.series !== 'object') {
            return { version: 1, updatedAt: new Date().toISOString(), series: {} };
        }
        return j;
    } catch {
        return { version: 1, updatedAt: new Date().toISOString(), series: {} };
    }
};

export const saveMartingaleState = (filePath: string, state: MartingaleStateFile): void => {
    const abs = path.resolve(filePath);
    const dir = path.dirname(abs);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    const next: MartingaleStateFile = { ...state, updatedAt: new Date().toISOString() };
    fs.writeFileSync(abs, JSON.stringify(next, null, 2), 'utf8');
};

export const getSeries = (
    state: MartingaleStateFile,
    asset: MartingaleAsset,
    interval: MartingaleIntervalKey
): MartingaleSeriesPersisted => {
    const k = seriesKey(asset, interval);
    if (!state.series[k]) {
        state.series[k] = emptySeries();
    }
    const ser = state.series[k];
    if (typeof ser.sessionRealizedPnlUsd !== 'number' || Number.isNaN(ser.sessionRealizedPnlUsd)) {
        ser.sessionRealizedPnlUsd = 0;
    }
    if (typeof ser.trendMartingaleRedeemTargetUsd !== 'number' || Number.isNaN(ser.trendMartingaleRedeemTargetUsd)) {
        ser.trendMartingaleRedeemTargetUsd = 0;
    }
    return ser;
};

export const stakeForStep = (baseUsd: number, stepIndex: number): number => {
    return baseUsd * Math.pow(2, Math.max(0, stepIndex));
};

const clampImpliedPrice = (p: number, fallback: number): number => {
    if (!Number.isFinite(p) || p <= 0) {
        return Math.min(0.99, Math.max(0.01, fallback));
    }
    return Math.min(0.99, Math.max(0.01, p));
};

/**
 * 下一笔目标名义：random 为 base×2^step；trend_follow 在 redeemTarget>0 时为 T×p/(1−p)（T=Σ 历史输局的 stake/entry），否则同首笔 base。
 */
export const nextStakeUsdForMartingale = (
    cfg: MartingaleRuntimeConfig,
    series: MartingaleSeriesPersisted,
    baseUsd: number,
    entryPriceForNextBet: number
): number => {
    const minU = cfg.minOrderUsd;
    const baseStake = Math.max(minU, stakeForStep(baseUsd, series.stepIndex));
    if (cfg.entrySideMode !== 'trend_follow') {
        return baseStake;
    }
    const tgt = series.trendMartingaleRedeemTargetUsd ?? 0;
    if (!(tgt > 0)) {
        return baseStake;
    }
    const p = clampImpliedPrice(entryPriceForNextBet, cfg.assumedEntryPrice);
    const oneMinus = Math.max(1e-9, 1 - p);
    const raw = tgt * (p / oneMinus);
    return Math.max(minU, raw);
};
