/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 按时间顺序遍历已收盘的 up/down 窗口，模拟随机方向 + 马丁倍投，并写入 Excel。
 * Generated By AI End (Cursor)
 */

import {
    ASSET_TO_SLUG_PREFIX,
    INTERVAL_SECONDS,
    martingaleHttpFetchOpts,
    seriesKey,
    type MartingaleAsset,
    type MartingaleIntervalKey,
    type MartingaleRuntimeConfig,
} from './martingaleConfig';
import { applyOutcomeToSeries } from './martingaleCore';
import {
    buildUpdownSlug,
    fetchMarketBySlug,
    floorToWindowStart,
    parseClobTokenIds,
    parseJsonArrayField,
    parseOutcomePrices,
    winningOutcomeIndex,
} from './martingaleMarket';
import { appendMartingaleExcelRow, type MartingaleExcelRow } from './martingaleExcel';
import { mulberry32 } from './martingaleRng';
import { getSeries, stakeForStep, type MartingaleStateFile } from './martingaleState';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const windowStartIso = (sec: number): string => {
    return new Date(sec * 1000).toISOString();
};

const entryPriceForSide = (m: { outcomePrices?: unknown }, idx: 0 | 1, fallback: number): number => {
    const prices = parseOutcomePrices(m.outcomePrices);
    const p = prices[idx];
    if (p != null && Number.isFinite(p) && p >= 0.01 && p <= 0.99) {
        return p;
    }
    return fallback;
};

export const runMartingaleBacktest = async (
    cfg: MartingaleRuntimeConfig
): Promise<{ rowsWritten: number; lines: string[] }> => {
    const requestGapMs = cfg.backtestRequestGapMs;
    const http = martingaleHttpFetchOpts(cfg);
    const lines: string[] = [];
    const rng = mulberry32(cfg.randomSeed ?? 0x9e3779b9);
    const nowSec = Math.floor(Date.now() / 1000);
    const state: MartingaleStateFile = { version: 1, updatedAt: new Date().toISOString(), series: {} };
    let totalRows = 0;
    for (const asset of cfg.assets) {
        for (const interval of cfg.intervals) {
            const intervalSec = INTERVAL_SECONDS[interval];
            const prefix = ASSET_TO_SLUG_PREFIX[asset];
            const endW = floorToWindowStart(nowSec, intervalSec);
            const startSec = nowSec - cfg.backtestDays * 86400;
            const startW = floorToWindowStart(startSec, intervalSec);
            const s = getSeries(state, asset, interval);
            let seriesRows = 0;
            for (let w = startW; w <= endW; w += intervalSec) {
                const slug = buildUpdownSlug(prefix, interval, w);
                const m = await fetchMarketBySlug(slug, http);
                if (requestGapMs > 0) {
                    await sleep(requestGapMs);
                }
                if (!m || !m.conditionId) {
                    continue;
                }
                if (!m.closed) {
                    continue;
                }
                const winIdx = winningOutcomeIndex(m);
                if (winIdx === null) {
                    continue;
                }
                const labels = parseJsonArrayField(m.outcomes);
                if (labels.length < 2) {
                    continue;
                }
                const idx = (rng() < 0.5 ? 0 : 1) as 0 | 1;
                const sideLabel = labels[idx] || String(idx);
                const stake = Math.max(cfg.minOrderUsd, stakeForStep(cfg.baseStakeUsd, s.stepIndex));
                const entryPx = entryPriceForSide(m, idx, cfg.assumedEntryPrice);
                const won = idx === winIdx;
                const settlement = applyOutcomeToSeries(s, cfg, won, stake, entryPx);
                const winLabel = labels[winIdx] || String(winIdx);
                const tokenIds = parseClobTokenIds(m);
                const tokenId = tokenIds[idx] || '';
                const assumedShares = stake / entryPx;
                if (settlement.note === 'loss_max_steps_reset') {
                    lines.push(
                        `[回测 ${seriesKey(asset, interval)}] ${slug} 达最大步数仍输，序列重置`
                    );
                }
                const row: MartingaleExcelRow = {
                    timeUtc: new Date().toISOString(),
                    asset,
                    interval,
                    slug,
                    windowStartUtc: windowStartIso(w),
                    sidePicked: sideLabel,
                    winningOutcome: winLabel,
                    stakeUsd: stake.toFixed(4),
                    stepIndex: String(settlement.stepBefore),
                    won: won ? 'Y' : 'N',
                    pnlRoundUsd: settlement.pnlUsd.toFixed(4),
                    cumulativeLossBeforeUsd: settlement.cumulativeLossBeforeUsd.toFixed(4),
                    stepAfter: String(settlement.stepAfter),
                    conditionId: String(m.conditionId || ''),
                    tokenId,
                    assumedShares: assumedShares.toFixed(6),
                    execPrice: entryPx.toFixed(6),
                    execMode: 'backtest',
                    discovery: 'slug',
                    notes: `backtest_closed_window|${settlement.note}`,
                };
                await appendMartingaleExcelRow(cfg.excelReportPath, row);
                seriesRows += 1;
                totalRows += 1;
            }
            lines.push(`[回测 ${seriesKey(asset, interval)}] 本序列收盘窗口写入 ${seriesRows} 行`);
        }
    }
    lines.push(`[回测汇总] 合计 ${totalRows} 行 -> ${cfg.excelReportPath}`);
    return { rowsWritten: totalRows, lines };
};
