/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 市场发现：优先 slug（含「下一窗」）；在开放盘中过滤即将截止的盘；兜底列表取窗口起点最新且未临期的市场。
 * Generated By AI End (Cursor)
 */

import fetchData from '../utils/fetchData';
import {
    ASSET_TO_SLUG_PREFIX,
    INTERVAL_SECONDS,
    martingaleHttpFetchOpts,
    type MartingaleAsset,
    type MartingaleIntervalKey,
    type MartingaleRuntimeConfig,
} from './martingaleConfig';
import {
    buildUpdownSlug,
    fetchMarketBySlug,
    floorToWindowStart,
    gammaWindowDurationSec,
    isMarketTooCloseToExpiry,
    type GammaMarketLite,
} from './martingaleMarket';

const UP_DOWN_SLUG_RE = /^(btc|eth|sol)-updown-(5m|15m)-(\d+)$/i;

export type DiscoveredOpen = {
    slug: string;
    market: GammaMarketLite;
    windowStartSec: number;
    discovery: 'slug' | 'gamma_list';
};

export type MartingaleDiscoveryResult =
    | { found: true; data: DiscoveredOpen }
    | { found: false; reason: string };

const extractSlugWindow = (slug: string): { prefix: string; interval: MartingaleIntervalKey; start: number } | null => {
    const m = slug.trim().match(UP_DOWN_SLUG_RE);
    if (!m) {
        return null;
    }
    const prefix = m[1].toLowerCase();
    const interval = m[2].toLowerCase() as MartingaleIntervalKey;
    const start = parseInt(m[3], 10);
    if (!Number.isFinite(start)) {
        return null;
    }
    if (interval !== '5m' && interval !== '15m') {
        return null;
    }
    return { prefix, interval, start };
};

const prefixMatchesAsset = (prefix: string, asset: MartingaleAsset): boolean => {
    return ASSET_TO_SLUG_PREFIX[asset] === prefix;
};

const parseGammaMarketsPayload = (raw: unknown): GammaMarketLite[] => {
    if (Array.isArray(raw)) {
        return raw as GammaMarketLite[];
    }
    if (raw && typeof raw === 'object') {
        const o = raw as Record<string, unknown>;
        const inner = o.markets ?? o.data;
        if (Array.isArray(inner)) {
            return inner as GammaMarketLite[];
        }
    }
    return [];
};

const withinSlugHorizon = (windowStart: number, base: number, intervalSec: number): boolean => {
    return windowStart <= base + intervalSec && windowStart >= base - intervalSec * 4;
};

/** endDate 与窗起点差若与期望周期差超过该秒数，视为非本周期盘（避免配置 5m 却命中 15m 实体窗） */
const GAMMA_DURATION_SLACK_SEC = 120;

const marketDurationMatchesSeriesInterval = (
    m: GammaMarketLite,
    windowStartSec: number,
    expectedIntervalSec: number
): boolean => {
    const dur = gammaWindowDurationSec(m, windowStartSec);
    if (dur == null) {
        return true;
    }
    return Math.abs(dur - expectedIntervalSec) <= GAMMA_DURATION_SLACK_SEC;
};

/** slug 中段必须与当前序列 interval 一致，防止 Gamma 列表等路径串入 15m/5m 错配。 */
const slugIntervalMatchesSeries = (slug: string, interval: MartingaleIntervalKey): boolean => {
    const parsed = extractSlugWindow(slug);
    return parsed !== null && parsed.interval === interval;
};

const pickNewestNotExpiringSoon = (
    items: DiscoveredOpen[],
    cfg: MartingaleRuntimeConfig,
    intervalSec: number,
    nowSec: number
): MartingaleDiscoveryResult => {
    if (items.length === 0) {
        return { found: false, reason: 'no_open_market' };
    }
    const ok = items.filter((x) => !isMarketTooCloseToExpiry(x.market, cfg.minRemainingSecToEnter));
    if (ok.length === 0) {
        return { found: false, reason: 'all_open_too_close_to_expiry' };
    }
    const currentWindowStart = floorToWindowStart(nowSec, intervalSec);
    ok.sort((a, b) => {
        const aCur = a.windowStartSec === currentWindowStart ? 1 : 0;
        const bCur = b.windowStartSec === currentWindowStart ? 1 : 0;
        if (aCur !== bCur) {
            return bCur - aCur;
        }
        return b.windowStartSec - a.windowStartSec;
    });
    return { found: true, data: ok[0] };
};

export const discoverOpenMarketForSeries = async (
    asset: MartingaleAsset,
    interval: MartingaleIntervalKey,
    cfg: MartingaleRuntimeConfig
): Promise<MartingaleDiscoveryResult> => {
    const http = martingaleHttpFetchOpts(cfg);
    const intervalSec = INTERVAL_SECONDS[interval];
    const prefix = ASSET_TO_SLUG_PREFIX[asset];
    const nowSec = Math.floor(Date.now() / 1000);
    const base = floorToWindowStart(nowSec, intervalSec);
    const tries: number[] = [];
    tries.push(base);
    tries.push(base + intervalSec);
    for (let i = 1; i <= cfg.slugLookbackWindows; i++) {
        tries.push(base - i * intervalSec);
    }
    const slugHits: DiscoveredOpen[] = [];
    for (const w of tries) {
        if (w < 0) {
            continue;
        }
        const slug = buildUpdownSlug(prefix, interval, w);
        const m = await fetchMarketBySlug(slug, http);
        if (m && m.conditionId && !m.closed) {
            const parsed = extractSlugWindow(slug);
            const windowStartSec = parsed?.start ?? w;
            if (!marketDurationMatchesSeriesInterval(m, windowStartSec, intervalSec)) {
                continue;
            }
            slugHits.push({ slug, market: m, windowStartSec, discovery: 'slug' });
        }
    }
    const slugPick = pickNewestNotExpiringSoon(slugHits, cfg, intervalSec, nowSec);
    if (slugPick.found) {
        if (!slugIntervalMatchesSeries(slugPick.data.slug, interval)) {
            return { found: false, reason: 'slug_interval_mismatch' };
        }
        return slugPick;
    }
    if (!cfg.gammaFallbackEnabled) {
        return slugPick;
    }
    const listHits: DiscoveredOpen[] = [];
    const pageSize = 100;
    const maxPages = Math.max(1, cfg.gammaFallbackMaxPages);
    for (let page = 0; page < maxPages; page++) {
        const offset = page * pageSize;
        const url = `https://gamma-api.polymarket.com/markets?active=true&closed=false&limit=${pageSize}&offset=${offset}`;
        const raw = await fetchData(url, http);
        const list = parseGammaMarketsPayload(raw);
        for (const m of list) {
            const slug = String(m.slug || '');
            const parsed = extractSlugWindow(slug);
            if (!parsed || !prefixMatchesAsset(parsed.prefix, asset) || parsed.interval !== interval) {
                continue;
            }
            if (m.closed) {
                continue;
            }
            if (!withinSlugHorizon(parsed.start, base, intervalSec)) {
                continue;
            }
            if (!marketDurationMatchesSeriesInterval(m, parsed.start, intervalSec)) {
                continue;
            }
            listHits.push({
                slug,
                market: m,
                windowStartSec: parsed.start,
                discovery: 'gamma_list',
            });
        }
        if (list.length < pageSize) {
            break;
        }
    }
    const listPick = pickNewestNotExpiringSoon(listHits, cfg, intervalSec, nowSec);
    if (listPick.found) {
        if (!slugIntervalMatchesSeries(listPick.data.slug, interval)) {
            return { found: false, reason: 'slug_interval_mismatch' };
        }
        return listPick;
    }
    if (listHits.length > 0) {
        return { found: false, reason: 'all_open_too_close_to_expiry' };
    }
    return slugPick;
};
