/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 单轮扫描：结算已关闭挂单 → 发现开放市场（slug + Gamma 列表兜底）→ 按配置选边 → 模拟或 CLOB 实盘下单。
 * Generated By AI End (Cursor)
 */

import type { ClobClient } from '@polymarket/clob-client';
import Logger from '../utils/logger';
import {
    notifyMartingaleOrderFilled,
    notifyMartingaleSettled,
    notifyMartingaleTrendSideMismatch,
} from '../utils/emailNotifier';
import {
    INTERVAL_SECONDS,
    martingaleHttpFetchOpts,
    seriesKey,
    type MartingaleAsset,
    type MartingaleIntervalKey,
    type MartingaleRuntimeConfig,
} from './martingaleConfig';
import { applyOutcomeToSeries, type SettlementOutcome } from './martingaleCore';
import { discoverOpenMarketForSeries } from './martingaleDiscovery';
import { provisionalWinnerFromClobMidPrices } from './martingaleBookSettle';
import {
    formatMartingaleTrendHintFromResolved,
    leadingOutcomeLabelFromResolvedTrend,
    resolveMartingaleBinaryTrend,
    type MartingaleBinaryTrend,
} from './martingaleBookTrend';
import { appendMartingaleExcelRow, type MartingaleExcelRow } from './martingaleExcel';
import { martingaleMarketBuyUsd } from './martingaleLiveOrders';
import { markToMarketUnrealizedUsd } from './martingalePnl';
import { fetchClobLightPriceUsdCached } from '../utils/clobPublicPrice';
import {
    fetchMarketBySlug,
    floorToWindowStart,
    parseClobTokenIds,
    parseJsonArrayField,
    parseOutcomePrices,
    provisionalWinnerFromGammaPrices,
    remainingSecondsUntilEnd,
    winningOutcomeIndex,
    type GammaMarketLite,
} from './martingaleMarket';
import {
    formatCountdownClockZh,
    formatRemainingUntilEndZh,
    martingaleConsoleMarketUrl,
    shortConditionId,
    shortTokenId,
} from './martingalePolymarketLinks';
import {
    getSeries,
    loadMartingaleState,
    nextStakeUsdForMartingale,
    saveMartingaleState,
    stakeForStep,
    type MartingaleStateFile,
    type MartingaleSeriesPersisted,
} from './martingaleState';

const pendingSettlementLastLogMs = new Map<string, number>();
const pendingCompactTickLastLogMs = new Map<string, number>();
/** 启动阶段跳过开仓时的单行日志节流（key = 序列:原因），避免 2s 轮询刷屏。 */
const martingaleStartupPhaseSkipLogLastMs = new Map<string, number>();
/** 趋势跟单未满足条件时的单行日志节流 */
const trendEntrySkipLogLastMs = new Map<string, number>();
/**
 * 本进程内该序列已完成「启动等下一窗」首单约束（已成功挂过单），结算后再 discover 不再套用冷启动首单规则。
 */
const martingaleStartupDeferralSatisfiedBySeries = new Set<string>();

/** 趋势跟单：每序列在本 windowStart 内「首次穿越阈值」锁定的侧（另一侧后达阈值也不改） */
const trendFirstHitBySeriesKey = new Map<
    string,
    { windowStartSec: number; lockedSide: 0 | 1 | null; prevP0: number | null; prevP1: number | null }
>();

/** 押边≠偏高告警邮件：每序列+slug+窗起点只发一次，恢复一致或平盘时清除 key */
const trendMismatchMailSentKeys = new Set<string>();

/** 模拟盘「启动清空 state」时调用，避免旧节流 Map / 首单集合与空 state 不一致 */
export const resetMartingaleRunnerSessionCaches = (): void => {
    pendingSettlementLastLogMs.clear();
    pendingCompactTickLastLogMs.clear();
    martingaleStartupPhaseSkipLogLastMs.clear();
    trendEntrySkipLogLastMs.clear();
    trendFirstHitBySeriesKey.clear();
    martingaleStartupDeferralSatisfiedBySeries.clear();
    trendMismatchMailSentKeys.clear();
};

export type MartingaleLogLine = string;

export type MartingaleRunOptions = {
    execution: 'dry' | 'live';
    clob?: ClobClient;
};

const windowStartIso = (sec: number): string => {
    return new Date(sec * 1000).toISOString();
};

const fireMartingaleMail = (fn: () => Promise<void>): void => {
    void fn().catch((e) =>
        Logger.warning(`[马丁邮件] 发送失败: ${e instanceof Error ? e.message : String(e)}`)
    );
};

// Generated By AI Start (Cursor)
const martingaleSideLabelMatchesLeading = (sideLabel: string, leading: string): boolean => {
    return sideLabel.trim().toLowerCase() === leading.trim().toLowerCase();
};

/**
 * 在输出「待收盘」日志且能解析两侧价时：趋势跟单下若押边与偏高侧不一致则发邮件（每挂单窗去重）。
 */
const maybeFireTrendMismatchAlertOnPendingLog = (
    cfg: MartingaleRuntimeConfig,
    seriesK: string,
    ob: NonNullable<MartingaleSeriesPersisted['openBet']>,
    trendTr: MartingaleBinaryTrend,
    trendHintLine: string
): void => {
    if (!cfg.emailOnTrendMismatch || cfg.entrySideMode !== 'trend_follow') {
        return;
    }
    const dedupeKey = `${seriesK}|${ob.slug}|${ob.windowStartSec}`;
    const lead = leadingOutcomeLabelFromResolvedTrend(trendTr);
    if (lead == null) {
        trendMismatchMailSentKeys.delete(dedupeKey);
        return;
    }
    if (martingaleSideLabelMatchesLeading(ob.sideLabel, lead)) {
        trendMismatchMailSentKeys.delete(dedupeKey);
        return;
    }
    if (trendMismatchMailSentKeys.has(dedupeKey)) {
        return;
    }
    trendMismatchMailSentKeys.add(dedupeKey);
    fireMartingaleMail(() =>
        notifyMartingaleTrendSideMismatch(
            {
                seriesKey: seriesK,
                sideLabel: ob.sideLabel,
                leadingLabel: lead,
                trendHintLine: trendHintLine,
                slug: ob.slug,
                stakeUsd: ob.stakeUsd,
            },
            cfg.emailOnTrendMismatch
        )
    );
};
// Generated By AI End (Cursor)

/** 启动阶段「跳过开仓」单行日志节流，避免轮询过密刷屏。 */
const shouldLogStartupPhaseSkip = (cfg: MartingaleRuntimeConfig, dedupeKey: string): boolean => {
    if (cfg.logVerbose) {
        return true;
    }
    const minMs = Math.max(10_000, cfg.pendingCountdownLogSec * 1000);
    const prev = martingaleStartupPhaseSkipLogLastMs.get(dedupeKey) ?? 0;
    const nowMs = Date.now();
    if (nowMs - prev < minMs) {
        return false;
    }
    martingaleStartupPhaseSkipLogLastMs.set(dedupeKey, nowMs);
    return true;
};

const shouldLogTrendEntrySkip = (cfg: MartingaleRuntimeConfig, dedupeKey: string): boolean => {
    if (cfg.logVerbose) {
        return true;
    }
    const minMs = Math.max(10_000, cfg.pendingCountdownLogSec * 1000);
    const prev = trendEntrySkipLogLastMs.get(dedupeKey) ?? 0;
    const nowMs = Date.now();
    if (nowMs - prev < minMs) {
        return false;
    }
    trendEntrySkipLogLastMs.set(dedupeKey, nowMs);
    return true;
};

/** 理论交易窗的 UTC 起止（slug 窗起点 + 周期秒数），用于日志对照「上一盘 / 下一盘」 */
const formatTheoryWindowRangeUtc = (windowStartSec: number, intervalSec: number): string => {
    return `${windowStartIso(windowStartSec)} → ${windowStartIso(windowStartSec + intervalSec)} (窗长 ${intervalSec}s)`;
};

/** 结算后下一笔名义：random 为 2^step×基；trend_follow 为按 Σ(stake/p) 与下一笔隐含价推算 T×p/(1−p) */
const martingaleNextStakeStrategyZh = (
    won: boolean,
    settlement: SettlementOutcome,
    cfg: MartingaleRuntimeConfig,
    series: { trendMartingaleRedeemTargetUsd?: number }
): string => {
    if (cfg.entrySideMode === 'trend_follow') {
        if (won) {
            return '下一笔名义: 赢后重置 → 1× 基础额（趋势累计赎回目标已清零）';
        }
        if (settlement.note === 'loss_max_steps_reset') {
            return '下一笔名义: 已达最大连亏步数已重置 → 1× 基础额（趋势累计赎回目标已清零）';
        }
        const tgt = series.trendMartingaleRedeemTargetUsd ?? 0;
        if (tgt > 0) {
            return `下一笔名义: 趋势回补 · 累计赎回目标 T≈${tgt.toFixed(4)} USD（各输局 stake/入场价之和）；下一笔按隐含价 p 用 T×p/(1−p) 算名义（约第 ${settlement.stepAfter + 1} 档）`;
        }
        return `下一笔名义: 趋势跟单 · 第 ${settlement.stepAfter + 1} 档仍用基础额（尚无累计 T）`;
    }
    if (won) {
        return '下一笔名义: 赢后重置 → 1× 基础额';
    }
    if (settlement.note === 'loss_max_steps_reset') {
        return '下一笔名义: 已达最大连亏步数已重置 → 1× 基础额';
    }
    return `下一笔名义: 输后倍投 → 第 ${settlement.stepAfter + 1} 档 · 约 2^${settlement.stepAfter}×基础额（共 ${cfg.maxMartingaleSteps} 档上限）`;
};

const fmtSignedUsd = (n: number): string => {
    const sign = n >= 0 ? '+' : '';
    return `${sign}${n.toFixed(2)}U`;
};

/** 本序列（仅该 asset:interval）的马丁档位：1=首档 1× 基，与其它市场无关 */
const martingaleTierCompact = (stepIndex: number, maxMartingaleSteps: number): string => {
    const tier = Math.max(1, stepIndex + 1);
    return `本序列档${tier}/${maxMartingaleSteps}(2^${stepIndex}×基)`;
};

const sessionPnlSummary = (
    sessionRealized: number,
    stepIndex: number,
    maxMartingaleSteps: number
): string =>
    `累计已实现${fmtSignedUsd(sessionRealized)} | ${martingaleTierCompact(stepIndex, maxMartingaleSteps)}`;

/** 当前挂单在本马丁链中为第几笔下注、已倍投几次（stepIndex=0 为首注未倍投） */
const martingaleBetRoundCompactZh = (stepIndex: number): string => {
    const chainN = stepIndex + 1;
    if (stepIndex <= 0) {
        return `第${chainN}笔·首注未倍投·1×基`;
    }
    return `第${chainN}笔·已倍投${stepIndex}次·2^${stepIndex}×基`;
};

const martingaleBetRoundVerboseZh = (stepIndex: number): string => {
    const chainN = stepIndex + 1;
    if (stepIndex <= 0) {
        return `本挂单为马丁链第 ${chainN} 笔：首注，尚未倍投，名义倍数 1× 基础额。`;
    }
    return `本挂单为马丁链第 ${chainN} 笔：已连续倍投 ${stepIndex} 次，当前名义倍数 2^${stepIndex}× 基础额。`;
};

type MartingalePollAccel = { useFastPoll: boolean; useUltraFastPoll: boolean };

const martingaleModeLabelZh = (cfg: MartingaleRuntimeConfig): string => {
    return cfg.entrySideMode === 'trend_follow' ? '趋势跟单' : '随机';
};

/**
 * 挂单未结算时：估算若本笔结算为亏，下一笔目标名义（趋势：T+本笔/p 后按 T×p/(1−p)，预览 p 用本笔入场价；随机：2^(step+1)×基）。
 */
const estimateNextStakeIfCurrentBetLosesUsd = async (
    cfg: MartingaleRuntimeConfig,
    s: MartingaleSeriesPersisted,
    ob: NonNullable<MartingaleSeriesPersisted['openBet']>,
    stakeBaseUsd: number
): Promise<{ stakeUsd: number }> => {
    if (s.stepIndex >= cfg.maxMartingaleSteps - 1) {
        const st = Math.max(cfg.minOrderUsd, stakeForStep(stakeBaseUsd, 0));
        return { stakeUsd: st };
    }
    if (cfg.entrySideMode !== 'trend_follow') {
        const st = Math.max(cfg.minOrderUsd, stakeForStep(stakeBaseUsd, s.stepIndex + 1));
        return { stakeUsd: st };
    }
    const pCur = Math.min(0.99, Math.max(0.01, ob.entryPriceUsed ?? cfg.assumedEntryPrice));
    const T_if = (s.trendMartingaleRedeemTargetUsd ?? 0) + ob.stakeUsd / pCur;
    // Generated By AI Start (Cursor)
    // 预览「下档」时 T×p/(1−p) 的 p 与本笔 T 中的分母一致（本笔入场隐含价），不用当刻 CLOB。
    // 当窗末若用现货 p→1，p/(1−p) 会虚高，与下一窗新盘 discover 后再入场的价格无关，易误导控制台。
    // Generated By AI End (Cursor)
    const synthetic: MartingaleSeriesPersisted = {
        stepIndex: s.stepIndex + 1,
        cumulativeLossUsdInSeries: s.cumulativeLossUsdInSeries,
        sessionRealizedPnlUsd: s.sessionRealizedPnlUsd,
        trendMartingaleRedeemTargetUsd: T_if,
        openBet: s.openBet,
    };
    const st = nextStakeUsdForMartingale(cfg, synthetic, stakeBaseUsd, pCur);
    return { stakeUsd: st };
};

const trySettleOpenBet = async (
    cfg: MartingaleRuntimeConfig,
    state: MartingaleStateFile,
    asset: MartingaleAsset,
    interval: MartingaleIntervalKey,
    lines: MartingaleLogLine[],
    accel: MartingalePollAccel | undefined,
    stakeBaseUsd: number
): Promise<boolean> => {
    const s = getSeries(state, asset, interval);
    const ob = s.openBet;
    if (!ob) {
        return false;
    }
    const k = seriesKey(asset, interval);
    const m = await fetchMarketBySlug(ob.slug, martingaleHttpFetchOpts(cfg));
    const nowMs = Date.now();
    const verboseMs =
        cfg.waitingSettlementLogSec <= 0 ? 0 : cfg.waitingSettlementLogSec * 1000;
    const prevVerbose = pendingSettlementLastLogMs.get(k) ?? 0;
    const shouldLogVerbosePending =
        cfg.logVerbose && (verboseMs === 0 || nowMs - prevVerbose >= verboseMs);
    const compactMs =
        cfg.pendingCountdownLogSec <= 0 ? 0 : cfg.pendingCountdownLogSec * 1000;
    const prevCompact = pendingCompactTickLastLogMs.get(k) ?? 0;
    const shouldLogCompactPending =
        !cfg.logVerbose && (compactMs === 0 || nowMs - prevCompact >= compactMs);

    if (!m) {
        if (accel) {
            accel.useFastPoll = true;
        }
        const shouldLog = cfg.logVerbose ? shouldLogVerbosePending : shouldLogCompactPending;
        if (shouldLog) {
            if (cfg.logVerbose) {
                pendingSettlementLastLogMs.set(k, nowMs);
            } else {
                pendingCompactTickLastLogMs.set(k, nowMs);
            }
            const url = martingaleConsoleMarketUrl(ob.slug);
            const nextIfLoseFail = await estimateNextStakeIfCurrentBetLosesUsd(cfg, s, ob, stakeBaseUsd);
            const modeFail = martingaleModeLabelZh(cfg);
            if (cfg.logVerbose) {
                lines.push(
                    [
                        `──────── 马丁格尔 · 挂单等待中 [${k}] ────────`,
                        `马丁模式: ${modeFail}`,
                        `若本挂单亏损，下一笔目标名义约: ${nextIfLoseFail.stakeUsd.toFixed(2)} USD（估算）`,
                        `序列键 [${k}]：BTC/ETH/SOL 与 5m/15m 各自独立计数，互不共用马丁档位。`,
                        `Gamma 暂无法拉取该 slug（404 或网络异常），下一巡继续重试。`,
                        `网页: ${url}`,
                        `slug: ${ob.slug}`,
                        martingaleBetRoundVerboseZh(s.stepIndex),
                        `押边: ${ob.sideLabel} | 名义: ${ob.stakeUsd.toFixed(4)} USD`,
                        sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps),
                    ]
                        .filter(Boolean)
                        .join('\n')
                );
            } else {
                lines.push(
                    [
                        `⚠ [${k}] 待结算·拉盘失败 | 模式:${modeFail} | 若本笔亏→下档≈${nextIfLoseFail.stakeUsd.toFixed(2)}U | ${martingaleBetRoundCompactZh(s.stepIndex)}`,
                        `${ob.sideLabel} ${ob.stakeUsd.toFixed(2)}U | ${sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps)}`,
                        `slug: ${ob.slug}`,
                        url,
                    ].join('\n')
                );
            }
        }
        return false;
    }
    const intervalSec = INTERVAL_SECONDS[interval];
    const windowEndSec = ob.windowStartSec + intervalSec;
    const nowSec = Math.floor(Date.now() / 1000);
    let resolvedWinIdx: number | null = null;
    let usedForceSettle = false;
    let usedBookSettle = false;
    if (m.closed) {
        resolvedWinIdx = winningOutcomeIndex(m);
    } else if (
        cfg.bookSettleAfterWindowSec > 0 &&
        nowSec >= windowEndSec + cfg.bookSettleAfterWindowSec
    ) {
        const bookWin = await provisionalWinnerFromClobMidPrices(m, cfg.bookSettleMinSpread);
        if (bookWin != null) {
            resolvedWinIdx = bookWin;
            usedBookSettle = true;
        }
    }
    if (resolvedWinIdx === null && !m.closed) {
        if (
            cfg.forceSettleGraceAfterWindowSec > 0 &&
            nowSec >= windowEndSec + cfg.forceSettleGraceAfterWindowSec
        ) {
            const prov = provisionalWinnerFromGammaPrices(m);
            if (prov != null) {
                resolvedWinIdx = prov;
                usedForceSettle = true;
            }
        }
    }
    if (resolvedWinIdx === null && !m.closed) {
        const remSec = remainingSecondsUntilEnd(m);
        // Gamma endDate 已过期，或已超过本窗理论结束：加速轮询 +（见下）控制过期日志频率
        const aggressiveExpireOrPastWindow =
            (remSec !== null && remSec < 0) || nowSec >= windowEndSec;
        if (
            accel &&
            (nowSec >= windowEndSec ||
                (remSec !== null &&
                    (remSec < 0 ||
                        (cfg.nearClosePollThresholdSec > 0 &&
                            remSec < cfg.nearClosePollThresholdSec))))
        ) {
            accel.useFastPoll = true;
        }
        if (accel && aggressiveExpireOrPastWindow) {
            accel.useUltraFastPoll = true;
        }
        // 常规待收盘心跳间隔（秒→毫秒）；0 表示不节流
        const compactTickMs =
            cfg.pendingCountdownLogSec <= 0 ? 0 : cfg.pendingCountdownLogSec * 1000;
        // 已过期/已过理论窗时：轮询仍可很快，但紧凑日志至少隔本值，避免每 2s 重复整段「已过期」
        const expiredHeartbeatMinMs = cfg.pendingExpiredHeartbeatMinSec * 1000;
        const effectiveCompactMs =
            !cfg.logVerbose && aggressiveExpireOrPastWindow
                ? Math.max(compactTickMs, expiredHeartbeatMinMs)
                : compactTickMs;
        const shouldLogCompactThis =
            effectiveCompactMs === 0 || nowMs - prevCompact >= effectiveCompactMs;
        const shouldLog = cfg.logVerbose ? shouldLogVerbosePending : shouldLogCompactThis;
        if (shouldLog) {
            if (cfg.logVerbose) {
                pendingSettlementLastLogMs.set(k, nowMs);
            } else {
                pendingCompactTickLastLogMs.set(k, nowMs);
            }
            const windowEndIso = new Date(windowEndSec * 1000).toISOString();
            const secPastTheoryEnd = Math.max(0, nowSec - windowEndSec);
            const pastTheoryEnd = secPastTheoryEnd > 120;
            const url = martingaleConsoleMarketUrl(ob.slug);
            const qFull = (m.question && String(m.question).trim()) || '（无题目）';
            const trendTr = await resolveMartingaleBinaryTrend(m);
            const trendHint = trendTr ? formatMartingaleTrendHintFromResolved(trendTr) : null;
            const trendParen = trendHint ? `（${trendHint}）` : '';
            if (trendTr && trendHint) {
                maybeFireTrendMismatchAlertOnPendingLog(cfg, k, ob, trendTr, trendHint);
            }
            const nextIfLose = await estimateNextStakeIfCurrentBetLosesUsd(cfg, s, ob, stakeBaseUsd);
            const modeZh = martingaleModeLabelZh(cfg);
            if (cfg.logVerbose) {
                const overdueNote = pastTheoryEnd
                    ? `⚠ 本窗理论结束至今已逾期 ${secPastTheoryEnd}s，Gamma 仍 closed=false。下一单须等本笔结算。更快：可设 MARTINGALE_BOOK_SETTLE_AFTER_WINDOW_SEC（CLOB 两侧价谁高谁赢）或调小 MARTINGALE_FORCE_SETTLE_GRACE_AFTER_WINDOW_SEC（Gamma 价推断）。`
                    : '';
                lines.push(
                    [
                        `──────── 马丁格尔 · 挂单等待中 [${k}] ────────`,
                        `马丁模式: ${modeZh}`,
                        `若本挂单亏损，下一笔目标名义约: ${nextIfLose.stakeUsd.toFixed(2)} USD（估算）`,
                        `序列键 [${k}]：各「资产+周期」单独一条马丁链，档位不与其它键混用。`,
                        '监控逻辑：每轮用挂单 slug 请求 Gamma；closed=true 时结算并释放本序列，随后才会 discover 下一盘。',
                        '市场仍开放，未收盘故不结算；同一序列在收盘前不会再开新仓（避免同窗重复马丁）。',
                        `题目: ${qFull}`,
                        `网页: ${url}`,
                        `slug: ${ob.slug}`,
                        `本窗理论结束(UTC): ${windowEndIso}（窗长 ${intervalSec}s）`,
                        `距 endDate 倒计时: ${formatCountdownClockZh(m)}`,
                        martingaleBetRoundVerboseZh(s.stepIndex),
                        `押边: ${ob.sideLabel}${trendParen} | 名义: ${ob.stakeUsd.toFixed(4)} USD`,
                        (() => {
                            const uu = markToMarketUnrealizedUsd(m, ob);
                            return uu != null
                                ? `按 Gamma outcomePrices 浮动盈亏(估算): ${fmtSignedUsd(uu)}`
                                : '浮动盈亏: （现价不可用）';
                        })(),
                        sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps),
                        overdueNote,
                    ]
                        .filter(Boolean)
                        .join('\n')
                );
            } else {
                const qShort = qFull.length > 42 ? `${qFull.slice(0, 40)}…` : qFull;
                const uu = markToMarketUnrealizedUsd(m, ob);
                const floatPart =
                    uu != null ? `浮${fmtSignedUsd(uu)}(现价估)` : '浮n/a';
                const clock = formatCountdownClockZh(m);
                const roundZh = martingaleBetRoundCompactZh(s.stepIndex);
                const pendingCompact = [
                    `⏳ [${k}] 待收盘 | 倒计时${clock} | 模式:${modeZh} | 若本笔亏→下档≈${nextIfLose.stakeUsd.toFixed(2)}U`,
                    `${roundZh} | ${qShort}`,
                    `押边 ${ob.sideLabel}${trendParen} · 名义 ${ob.stakeUsd.toFixed(2)}U`,
                    `${floatPart} | ${sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps)}`,
                    url,
                ];
                if (pastTheoryEnd) {
                    pendingCompact.push(
                        `⚠ 理论窗已结束 ${secPastTheoryEnd}s，Gamma 仍未 closed | 可设 MARTINGALE_BOOK_SETTLE_AFTER_WINDOW_SEC 或调小 FORCE_SETTLE 宽限`
                    );
                }
                lines.push(pendingCompact.join('\n'));
            }
        }
        return false;
    }
    if (resolvedWinIdx === null) {
        const sk = seriesKey(asset, interval);
        const u = martingaleConsoleMarketUrl(ob.slug);
        if (cfg.logVerbose) {
            lines.push(
                [
                    `──────── 马丁格尔 · 结算异常 [${sk}] ────────`,
                    '已收盘但无法从 outcomePrices 判定胜负，请人工核对。',
                    `网页: ${u}`,
                    `slug: ${ob.slug}`,
                ].join('\n')
            );
        } else {
            lines.push([`✗ [${sk}] 结算异常·无法解析胜负`, `slug: ${ob.slug}`, u].join('\n'));
        }
        return false;
    }
    const winIdx = resolvedWinIdx;
    const labels = parseJsonArrayField(m.outcomes);
    const winLabel = labels[winIdx] || String(winIdx);
    const won = ob.sideIndex === winIdx;
    const entryPx = ob.entryPriceUsed ?? cfg.assumedEntryPrice;
    const settlement = applyOutcomeToSeries(s, cfg, won, ob.stakeUsd, entryPx);
    if (cfg.entrySideMode === 'trend_follow') {
        if (won || settlement.note === 'loss_max_steps_reset') {
            s.trendMartingaleRedeemTargetUsd = 0;
        } else if (!won) {
            const p = Math.min(0.99, Math.max(0.01, entryPx));
            s.trendMartingaleRedeemTargetUsd = (s.trendMartingaleRedeemTargetUsd ?? 0) + ob.stakeUsd / p;
        }
    } else {
        s.trendMartingaleRedeemTargetUsd = 0;
    }
    s.sessionRealizedPnlUsd = (s.sessionRealizedPnlUsd ?? 0) + settlement.pnlUsd;
    s.openBet = null;
    pendingSettlementLastLogMs.delete(k);
    pendingCompactTickLastLogMs.delete(k);
    const sharesStr =
        ob.assumedShares != null && Number.isFinite(ob.assumedShares)
            ? ob.assumedShares.toFixed(6)
            : '';
    const row: MartingaleExcelRow = {
        timeUtc: new Date().toISOString(),
        asset,
        interval,
        slug: ob.slug,
        windowStartUtc: windowStartIso(ob.windowStartSec),
        sidePicked: ob.sideLabel,
        winningOutcome: winLabel,
        stakeUsd: ob.stakeUsd.toFixed(4),
        stepIndex: String(settlement.stepBefore),
        won: won ? 'Y' : 'N',
        pnlRoundUsd: settlement.pnlUsd.toFixed(4),
        cumulativeLossBeforeUsd: settlement.cumulativeLossBeforeUsd.toFixed(4),
        stepAfter: String(settlement.stepAfter),
        conditionId: ob.conditionId || '',
        tokenId: ob.tokenId || '',
        assumedShares: sharesStr,
        execPrice: entryPx.toFixed(6),
        execMode: ob.execMode || 'dryrun',
        discovery: ob.discovery || '',
        notes: (() => {
            let n = settlement.note;
            if (usedBookSettle) {
                n = `${n}|book_settle_clob_mid`;
            }
            if (usedForceSettle) {
                n = `${n}|force_settle_gamma_lag`;
            }
            return n;
        })(),
    };
    await appendMartingaleExcelRow(cfg.excelReportPath, row);
    const q = (m.question && String(m.question).trim()) || '（Gamma 无题目）';
    const pageUrl = martingaleConsoleMarketUrl(ob.slug);
    const sk = seriesKey(asset, interval);
    const maxStepNote =
        settlement.note === 'loss_max_steps_reset'
            ? '⚠ 本链已达最大连亏次数，马丁步数已从 0 重新开始。'
            : '';
    const forceSettleNote = usedBookSettle
        ? '⚠ 本笔按 CLOB 两侧轻量价（midpoint/last）谁高谁赢推断结算；理论窗结束后延迟见 MARTINGALE_BOOK_SETTLE_AFTER_WINDOW_SEC；与官方 closed 可能不一致，风险自负（Excel notes book_settle_clob_mid）。'
        : usedForceSettle
          ? '⚠ 本笔因 Gamma 长期未 closed，已在理论窗结束+宽限后按 outcomePrices 推断结算（见 Excel notes force_settle_gamma_lag）。'
          : '';
    if (cfg.logVerbose) {
        lines.push(
            [
                `──────── 马丁格尔 · 已结算 [${sk}] ────────`,
                forceSettleNote,
                `题目: ${q}`,
                `网页: ${pageUrl}`,
                `slug: ${ob.slug}`,
                `conditionId: ${shortConditionId(ob.conditionId)}`,
                `曾押边: ${ob.sideLabel} | 结算结果: ${winLabel}`,
                `本局盈亏(按入场价${entryPx.toFixed(4)}计): ${fmtSignedUsd(settlement.pnlUsd)}（${won ? '盈利' : '亏损'}）`,
                `会话累计已实现: ${fmtSignedUsd(s.sessionRealizedPnlUsd)}`,
                `已结束盘(理论窗,UTC): ${formatTheoryWindowRangeUtc(ob.windowStartSec, intervalSec)}`,
                martingaleNextStakeStrategyZh(won, settlement, cfg, s),
                '本帧内接着 discover 下一时间段（如 11:05→11:10）并在无其它挂单阻塞时挂新单。',
                `下一档位: 第 ${settlement.stepAfter + 1} 档 / 共 ${cfg.maxMartingaleSteps}（内部 stepIndex=${settlement.stepAfter}；若赢则重置为第 1 档）`,
                maxStepNote,
            ]
                .filter(Boolean)
                .join('\n')
        );
    } else {
        const w = won ? '赢' : '输';
        const pnlWord = won ? '赚' : '亏';
        const forceTag = usedBookSettle ? '⚡订单簿推断·' : usedForceSettle ? '⚡逾期推断·' : '';
        const settleCompact = [
            `✓ [${sk}] ${forceTag}已结算${w} | 本局${pnlWord}${fmtSignedUsd(settlement.pnlUsd)}(入@${entryPx.toFixed(3)})`,
            `会话累计${fmtSignedUsd(s.sessionRealizedPnlUsd)} | 下一档${settlement.stepAfter + 1}/${cfg.maxMartingaleSteps}`,
            `已结束盘 ${formatTheoryWindowRangeUtc(ob.windowStartSec, intervalSec)}`,
            martingaleNextStakeStrategyZh(won, settlement, cfg, s),
            '本帧内将 discover 下一时间段并挂新单',
            pageUrl,
        ];
        if (maxStepNote) {
            settleCompact.push(maxStepNote);
        }
        lines.push(settleCompact.join('\n'));
    }
    const execModeSettle = ob.execMode === 'live' ? 'live' : 'dryrun';
    const nextStakeZhMail = martingaleNextStakeStrategyZh(won, settlement, cfg, s);
    fireMartingaleMail(() =>
        notifyMartingaleSettled(
            {
                seriesKey: sk,
                execMode: execModeSettle,
                sideLabel: ob.sideLabel,
                winningOutcome: winLabel,
                won,
                pnlRoundUsd: settlement.pnlUsd,
                sessionRealizedPnlUsd: s.sessionRealizedPnlUsd,
                entryPrice: entryPx,
                slug: ob.slug,
                question: q,
                theoryWindowUtc: formatTheoryWindowRangeUtc(ob.windowStartSec, intervalSec),
                stepAfter: settlement.stepAfter,
                maxSteps: cfg.maxMartingaleSteps,
                nextStakeZh: nextStakeZhMail,
                usedForceSettle,
                usedBookSettle,
            },
            cfg.emailOnSettle
        )
    );
    return true;
};

const randomSideIndex = (rng: () => number): 0 | 1 => {
    return rng() < 0.5 ? 0 : 1;
};

const trendFirstHitStateForWindow = (
    sk: string,
    windowStartSec: number
): { windowStartSec: number; lockedSide: 0 | 1 | null; prevP0: number | null; prevP1: number | null } => {
    const cur = trendFirstHitBySeriesKey.get(sk);
    if (!cur || cur.windowStartSec !== windowStartSec) {
        const next = {
            windowStartSec,
            lockedSide: null as 0 | 1 | null,
            prevP0: null as number | null,
            prevP1: null as number | null,
        };
        trendFirstHitBySeriesKey.set(sk, next);
        return next;
    }
    return cur;
};

/**
 * 新开仓选边：random 用 RNG；trend_follow 用本窗「首次从低于阈值抬升到 ≥ 阈值」的一侧锁边（另一侧后达阈值不改），锁定后本窗内始终押该侧。
 */
const resolveEntrySideIndex = async (
    cfg: MartingaleRuntimeConfig,
    rng: () => number,
    market: GammaMarketLite,
    sk: string,
    windowStartSec: number,
    intervalSec: number,
    slug: string,
    lines: MartingaleLogLine[]
): Promise<0 | 1 | null> => {
    if (cfg.entrySideMode !== 'trend_follow') {
        return randomSideIndex(rng);
    }
    // Generated By AI Start (Cursor)
    const pushTrendDiscoverFootnote = (): void => {
        const winRange = formatTheoryWindowRangeUtc(windowStartSec, intervalSec);
        const pageUrl = martingaleConsoleMarketUrl(slug);
        lines.push(
            `  └ 跟盘窗(每轮 discover 刷新，优先当前 wall clock 理论格之开放盘) | ${winRange} | ${pageUrl}`
        );
    };
    // Generated By AI End (Cursor)
    const tr = await resolveMartingaleBinaryTrend(market);
    if (!tr) {
        if (shouldLogTrendEntrySkip(cfg, `${sk}:trend_no_prices:${windowStartSec}`)) {
            lines.push(`— [${sk}] 趋势跟单·未取得两侧价 | 下轮再试`);
            pushTrendDiscoverFootnote();
        }
        return null;
    }
    const thr = cfg.trendFollowMinLeadingPrice;
    const st = trendFirstHitStateForWindow(sk, windowStartSec);
    if (st.lockedSide !== null) {
        st.prevP0 = tr.price0;
        st.prevP1 = tr.price1;
        return st.lockedSide;
    }
    const cross0 = tr.price0 >= thr && (st.prevP0 === null || st.prevP0 < thr);
    const cross1 = tr.price1 >= thr && (st.prevP1 === null || st.prevP1 < thr);
    if (!cross0 && !cross1) {
        st.prevP0 = tr.price0;
        st.prevP1 = tr.price1;
        if (shouldLogTrendEntrySkip(cfg, `${sk}:trend_wait_cross:${windowStartSec}`)) {
            lines.push(
                `— [${sk}] 趋势跟单·待本窗首次穿越≥${thr} | ${tr.label0}:${tr.price0.toFixed(2)} ${tr.label1}:${tr.price1.toFixed(2)} (${tr.source})`
            );
            pushTrendDiscoverFootnote();
        }
        return null;
    }
    let hitSide: 0 | 1;
    if (cross0 && !cross1) {
        hitSide = 0;
    } else if (!cross0 && cross1) {
        hitSide = 1;
    } else {
        hitSide = tr.price0 >= tr.price1 ? 0 : 1;
    }
    st.lockedSide = hitSide;
    st.prevP0 = tr.price0;
    st.prevP1 = tr.price1;
    const labHit = hitSide === 0 ? tr.label0 : tr.label1;
    const pxHit = hitSide === 0 ? tr.price0 : tr.price1;
    const labO = hitSide === 0 ? tr.label1 : tr.label0;
    const pxO = hitSide === 0 ? tr.price1 : tr.price0;
    if (cfg.logVerbose) {
        lines.push(
            [
                `──────── 马丁格尔 · 趋势穿越 [${sk}] ────────`,
                `本窗理论起点(UTC): ${windowStartIso(windowStartSec)} | slug: ${slug}`,
                `首次穿越 MARTINGALE_TREND_FOLLOW_MIN_LEADING_PRICE（≥${thr}，${tr.source}）：锁定押 ${labHit} 隐含≈${pxHit.toFixed(2)} | 另一侧 ${labO}:${pxO.toFixed(2)}`,
                '本帧将按锁定侧下单；若本窗内另一侧后再达阈值，不换边。',
            ].join('\n')
        );
    } else {
        lines.push(
            `◇ [${sk}] 趋势·已检测到穿越≥${thr}(${tr.source}) | 锁定买入 ${labHit}≈${pxHit.toFixed(2)} | ${labO}=${pxO.toFixed(2)} → 本帧发起该侧买单`
        );
    }
    return hitSide;
};

const entryPriceForSide = (m: { outcomePrices?: unknown }, idx: 0 | 1, fallback: number): number => {
    const prices = parseOutcomePrices(m.outcomePrices);
    const p = prices[idx];
    if (p != null && Number.isFinite(p) && p >= 0.01 && p <= 0.99) {
        return p;
    }
    return fallback;
};

/**
 * 单序列状态机（每个 asset+interval 独立）：
 * 1）若存在 openBet：每轮拉该 slug；closed 则结算、写 Excel、清 openBet、更新马丁 step。
 * 2）仅当 openBet 为空：discover 当前/下一窗等候选，剔除临期盘，取最新窗开新单。
 * 因此「上一笔未在 Gamma 标为收盘」前不会进入下一笔，避免用过时窗重复下注；下一窗由 discover 在清仓后实时选取。
 */
export type MartingaleOnceResult = {
    lines: MartingaleLogLine[];
    state: MartingaleStateFile;
    /** 本帧扫描结束后建议休眠秒数（临收盘/刚结算时更短） */
    nextSleepSec: number;
    /** 本帧内是否完成过至少一笔结算（便于外层立刻再扫一轮以接上下一窗） */
    settledThisPass: boolean;
};

export const runMartingaleOnce = async (
    cfg: MartingaleRuntimeConfig,
    rng: () => number,
    options: MartingaleRunOptions = { execution: 'dry' }
): Promise<MartingaleOnceResult> => {
    const lines: MartingaleLogLine[] = [];
    const state = loadMartingaleState(cfg.stateFilePath);
    const execution = options.execution;
    const clob = options.clob;
    const defaultPollSec =
        execution === 'live' ? cfg.pollIntervalSec : (cfg.dryRunPollIntervalSec ?? cfg.pollIntervalSec);
    if (execution === 'live' && !clob) {
        lines.push('live 模式需要传入 ClobClient');
        return { lines, state, nextSleepSec: defaultPollSec, settledThisPass: false };
    }
    const pollAccel: MartingalePollAccel = { useFastPoll: false, useUltraFastPoll: false };
    let settledAny = false;
    const baseUsdForStake =
        execution === 'live' ? cfg.baseStakeUsd : (cfg.dryRunBaseStakeUsd ?? cfg.baseStakeUsd);
    for (const asset of cfg.assets) {
        for (const interval of cfg.intervals) {
            const did = await trySettleOpenBet(cfg, state, asset, interval, lines, pollAccel, baseUsdForStake);
            if (did) {
                settledAny = true;
            }
            const s = getSeries(state, asset, interval);
            if (s.openBet) {
                continue;
            }
            const disc = await discoverOpenMarketForSeries(asset, interval, cfg);
            if (!disc.found) {
                const sk = seriesKey(asset, interval);
                const hint =
                    disc.reason === 'all_open_too_close_to_expiry'
                        ? '原因: 检测到有开放盘，但距 Gamma endDate 不足 MARTINGALE_MIN_REMAINING_SEC_TO_ENTER；开仓前还会用 slug 理论窗剩余再挡一层。'
                        : disc.reason === 'slug_interval_mismatch'
                          ? `原因: 候选 slug 与当前序列周期 ${interval} 不一致（例如配置 5m 却命中 -15m-）；已丢弃该候选。请核对 MARTINGALE_INTERVALS 与根目录 .env / .env.martingale 合并顺序。`
                          : '原因: 当前未找到符合条件的开放盘（slug 与 Gamma 列表兜底均未命中）。';
                if (cfg.logVerbose) {
                    lines.push(
                        [
                            `──────── 马丁格尔 · 未开新单 [${sk}] ────────`,
                            hint,
                            `提示: 可在浏览器打开 Polymarket，搜索「${asset} 15 minute」或「${asset} up down」对照盘口是否已切换新窗。`,
                        ].join('\n')
                    );
                } else {
                    const tag =
                        disc.reason === 'all_open_too_close_to_expiry'
                            ? '临期跳过'
                            : disc.reason === 'slug_interval_mismatch'
                              ? '周期不一致'
                              : '无盘';
                    lines.push([`— [${sk}] 本轮未开仓（${tag}）`, `原因码: ${disc.reason}`].join('\n'));
                }
                continue;
            }
            const picked = disc.data;
            const skOpen = seriesKey(asset, interval);
            const nowSecPick = Math.floor(Date.now() / 1000);
            const intervalSecPick = INTERVAL_SECONDS[interval];
            const theoryRemSecPick = picked.windowStartSec + intervalSecPick - nowSecPick;
            if (cfg.minRemainingSecToEnter > 0 && theoryRemSecPick < cfg.minRemainingSecToEnter) {
                const purlTr = martingaleConsoleMarketUrl(picked.slug);
                const remFloor = Math.max(0, Math.floor(theoryRemSecPick));
                if (cfg.logVerbose) {
                    lines.push(
                        [
                            `──────── 马丁格尔 · 新开单跳过 [${skOpen}] ────────`,
                            `slug 理论窗剩余约 ${remFloor}s，低于 MARTINGALE_MIN_REMAINING_SEC_TO_ENTER=${cfg.minRemainingSecToEnter}（与 Gamma endDate 无关，避免 endDate 缺失时尾盘误进）。`,
                            `windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                            `网页: ${purlTr}`,
                        ].join('\n')
                    );
                } else {
                    lines.push(
                        [
                            `— [${skOpen}] 跳过开仓·理论剩余≈${remFloor}s < ${cfg.minRemainingSecToEnter}s`,
                            purlTr,
                        ].join('\n')
                    );
                }
                continue;
            }
            if (cfg.startupWaitNextWindow && !martingaleStartupDeferralSatisfiedBySeries.has(skOpen)) {
                const slotStartPick = floorToWindowStart(nowSecPick, intervalSecPick);
                const purlSt = martingaleConsoleMarketUrl(picked.slug);
                if (nowSecPick < picked.windowStartSec) {
                    if (
                        shouldLogStartupPhaseSkip(cfg, `${skOpen}:before_window_start`)
                    ) {
                        if (cfg.logVerbose) {
                            lines.push(
                                [
                                    `──────── 马丁格尔 · 启动待命 [${skOpen}] ────────`,
                                    '已开启 MARTINGALE_STARTUP_WAIT_NEXT_WINDOW：discover 指向的窗理论起点尚未到（wall clock 未到 windowStart），首单暂不进场，待该窗开盘后再评估。',
                                    `windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                                    `网页: ${purlSt}`,
                                ].join('\n')
                            );
                        } else {
                            lines.push(
                                [
                                    `◇ [${skOpen}] 启动待命·下一窗理论未开始 | 待开盘后再进场`,
                                    `windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                                    purlSt,
                                ].join('\n')
                            );
                        }
                    }
                    continue;
                }
                if (picked.windowStartSec < slotStartPick) {
                    if (shouldLogStartupPhaseSkip(cfg, `${skOpen}:stale_slug`)) {
                        if (cfg.logVerbose) {
                            lines.push(
                                [
                                    `──────── 马丁格尔 · 启动待命 [${skOpen}] ────────`,
                                    'discover 仍指向早于当前理论窗起点的 slug（上一格窗），首单跳过，待 API 滚到当前/下一窗。',
                                    `picked windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                                    `当前理论窗起点(UTC): ${windowStartIso(slotStartPick)}`,
                                    `网页: ${purlSt}`,
                                ].join('\n')
                            );
                        } else {
                            lines.push(
                                [
                                    `◇ [${skOpen}] 启动待命·仍指向上窗 | 等 discover 对齐当前格`,
                                    `picked: ${windowStartIso(picked.windowStartSec)} | 理论当前格: ${windowStartIso(slotStartPick)}`,
                                    purlSt,
                                ].join('\n')
                            );
                        }
                    }
                    continue;
                }
                const intoSlotPick = nowSecPick - slotStartPick;
                if (
                    cfg.startupCurrentWindowGraceSec > 0 &&
                    picked.windowStartSec === slotStartPick &&
                    intoSlotPick > cfg.startupCurrentWindowGraceSec
                ) {
                    if (shouldLogStartupPhaseSkip(cfg, `${skOpen}:past_grace`)) {
                        if (cfg.logVerbose) {
                            lines.push(
                                [
                                    `──────── 马丁格尔 · 启动待命 [${skOpen}] ────────`,
                                    `本进程首单：当前理论窗已运行 ${intoSlotPick}s，超过 MARTINGALE_STARTUP_CURRENT_WINDOW_GRACE_SEC=${cfg.startupCurrentWindowGraceSec}，不追尾盘；等下一段 windowStart 再开仓。`,
                                    `windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                                    `网页: ${purlSt}`,
                                ].join('\n')
                            );
                        } else {
                            lines.push(
                                [
                                    `◇ [${skOpen}] 启动待命·本窗已过开头宽限(${cfg.startupCurrentWindowGraceSec}s) | 等下一窗`,
                                    `windowStart(UTC): ${windowStartIso(picked.windowStartSec)}`,
                                    purlSt,
                                ].join('\n')
                            );
                        }
                    }
                    continue;
                }
            }
            const labels = parseJsonArrayField(picked.market.outcomes);
            if (labels.length < 2) {
                const sk = seriesKey(asset, interval);
                if (cfg.logVerbose) {
                    lines.push(
                        [
                            `──────── 马丁格尔 · 跳过 [${sk}] ────────`,
                            `市场缺少 outcomes 字段，无法选边 | slug: ${picked.slug}`,
                            `网页: ${martingaleConsoleMarketUrl(picked.slug)}`,
                        ].join('\n')
                    );
                } else {
                    const ou = martingaleConsoleMarketUrl(picked.slug);
                    lines.push([`⚠ [${sk}] 缺 outcomes`, `slug: ${picked.slug}`, ou].join('\n'));
                }
                continue;
            }
            const skEntry = seriesKey(asset, interval);
            const idx = await resolveEntrySideIndex(
                cfg,
                rng,
                picked.market,
                skEntry,
                picked.windowStartSec,
                INTERVAL_SECONDS[interval],
                picked.slug,
                lines
            );
            if (idx === null) {
                continue;
            }
            const sideLabel = labels[idx] || (idx === 0 ? 'Up' : 'Down');
            const tokenIds = parseClobTokenIds(picked.market);
            const tokenId = tokenIds[idx] || '';
            let entryPx = entryPriceForSide(picked.market, idx, cfg.assumedEntryPrice);
            if (tokenId) {
                const clobP = await fetchClobLightPriceUsdCached(tokenId);
                if (clobP != null && Number.isFinite(clobP) && clobP >= 0.01 && clobP <= 0.99) {
                    entryPx = clobP;
                }
            }
            const stakeTarget = nextStakeUsdForMartingale(cfg, s, baseUsdForStake, entryPx);
            if (execution === 'live') {
                const sk = seriesKey(asset, interval);
                const purl = martingaleConsoleMarketUrl(picked.slug);
                if (!tokenId) {
                    if (cfg.logVerbose) {
                        lines.push(
                            [
                                `──────── 马丁格尔 · 实盘跳过 [${sk}] ────────`,
                                '无法从 Gamma 解析 clobTokenIds，不能下单。',
                                `网页: ${purl}`,
                                `slug: ${picked.slug}`,
                            ].join('\n')
                        );
                    } else {
                        lines.push(
                            [`✗ [${sk}] 实盘跳过·无 tokenId`, `slug: ${picked.slug}`, purl].join('\n')
                        );
                    }
                    continue;
                }
                lines.push(
                    [
                        `◇ [${sk}] 实盘发起吃单 | 目标名义 ${stakeTarget.toFixed(4)} USD | token ${shortTokenId(tokenId)} | FOK`,
                    ].join('\n')
                );
                const buy = await martingaleMarketBuyUsd(clob as ClobClient, tokenId, stakeTarget);
                if (!buy.ok) {
                    if (cfg.logVerbose) {
                        lines.push(
                            [
                                `──────── 马丁格尔 · 实盘失败 [${sk}] ────────`,
                                `原因: ${buy.reason}`,
                                `网页: ${purl}`,
                                `slug: ${picked.slug}`,
                            ].join('\n')
                        );
                    } else {
                        lines.push([`✗ [${sk}] 实盘失败 ${buy.reason}`, purl].join('\n'));
                    }
                    continue;
                }
                s.openBet = {
                    slug: picked.slug,
                    windowStartSec: picked.windowStartSec,
                    sideIndex: idx,
                    sideLabel,
                    stakeUsd: buy.usdcSpent,
                    conditionId: String(picked.market.conditionId || ''),
                    placedAtIso: new Date().toISOString(),
                    tokenId: buy.tokenId,
                    entryPriceUsed: buy.execPrice,
                    assumedShares: buy.shares,
                    execMode: 'live',
                    discovery: picked.discovery,
                };
                martingaleStartupDeferralSatisfiedBySeries.add(sk);
                const mq = (picked.market.question && String(picked.market.question).trim()) || '（Gamma 无题目）';
                if (cfg.logVerbose) {
                    lines.push(
                        [
                            `──────── 马丁格尔 · 实盘已成交 [${sk}] ────────`,
                            `下一时间段(理论窗,UTC): ${formatTheoryWindowRangeUtc(picked.windowStartSec, INTERVAL_SECONDS[interval])}`,
                            `题目: ${mq}`,
                            `网页: ${purl}`,
                            `slug: ${picked.slug}`,
                            `conditionId: ${shortConditionId(String(picked.market.conditionId || ''))}`,
                            `发现方式: ${picked.discovery === 'gamma_list' ? 'Gamma 列表兜底' : 'slug 直链'}`,
                            `方向: ${sideLabel} | 花费: ${buy.usdcSpent.toFixed(4)} USD | 均价≈${buy.execPrice.toFixed(4)} | 份额≈${buy.shares.toFixed(4)}`,
                            `tokenId: ${shortTokenId(buy.tokenId)}`,
                            `挂单时本序列档位: 第 ${s.stepIndex + 1} 档（内部 stepIndex=${s.stepIndex}，倍数≈基础×2^${s.stepIndex}）；与 [${sk}] 外其它资产/周期完全独立`,
                            martingaleBetRoundVerboseZh(s.stepIndex),
                            sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps),
                        ].join('\n')
                    );
                } else {
                    lines.push(
                        [
                            `◇ [${sk}] 跟踪下一时间段 | ${formatTheoryWindowRangeUtc(picked.windowStartSec, INTERVAL_SECONDS[interval])}`,
                            `✓ [${sk}] 实盘成交 ${sideLabel} ${buy.usdcSpent.toFixed(2)}U @${buy.execPrice.toFixed(3)} 股≈${buy.shares.toFixed(2)}`,
                            `${martingaleBetRoundCompactZh(s.stepIndex)} | ${sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps)}`,
                            purl,
                        ].join('\n')
                    );
                }
                fireMartingaleMail(() =>
                    notifyMartingaleOrderFilled(
                        {
                            seriesKey: sk,
                            execMode: 'live',
                            sideLabel,
                            stakeUsd: buy.usdcSpent,
                            entryPrice: buy.execPrice,
                            shares: buy.shares,
                            slug: picked.slug,
                            question: mq,
                            conditionId: String(picked.market.conditionId || ''),
                            tokenId: buy.tokenId,
                            stepTierZh: martingaleBetRoundCompactZh(s.stepIndex),
                            sessionRealizedPnlUsd: s.sessionRealizedPnlUsd,
                            theoryWindowUtc: formatTheoryWindowRangeUtc(
                                picked.windowStartSec,
                                INTERVAL_SECONDS[interval]
                            ),
                        },
                        cfg.emailOnOrder
                    )
                );
            } else {
                const assumedShares = stakeTarget / entryPx;
                const skd = seriesKey(asset, interval);
                lines.push(
                    `◇ [${skd}] 模拟下单（无链上）| ${sideLabel} | 名义 ${stakeTarget.toFixed(4)} USD | 参考价≈${entryPx.toFixed(4)} | 份额≈${assumedShares.toFixed(4)}`
                );
                s.openBet = {
                    slug: picked.slug,
                    windowStartSec: picked.windowStartSec,
                    sideIndex: idx,
                    sideLabel,
                    stakeUsd: stakeTarget,
                    conditionId: String(picked.market.conditionId || ''),
                    placedAtIso: new Date().toISOString(),
                    tokenId,
                    entryPriceUsed: entryPx,
                    assumedShares,
                    execMode: 'dryrun',
                    discovery: picked.discovery,
                };
                martingaleStartupDeferralSatisfiedBySeries.add(skOpen);
                const mq = (picked.market.question && String(picked.market.question).trim()) || '（Gamma 无题目）';
                const rem = formatRemainingUntilEndZh(picked.market);
                const purld = martingaleConsoleMarketUrl(picked.slug);
                if (cfg.logVerbose) {
                    lines.push(
                        [
                            `──────── 马丁格尔 · 模拟已挂单 [${skd}] ────────`,
                            `下一时间段(理论窗,UTC): ${formatTheoryWindowRangeUtc(picked.windowStartSec, INTERVAL_SECONDS[interval])}`,
                            `题目: ${mq}`,
                            `网页: ${purld}`,
                            `slug: ${picked.slug}`,
                            `conditionId: ${shortConditionId(String(picked.market.conditionId || ''))}`,
                            `距收盘剩余: ${rem}`,
                            `发现方式: ${picked.discovery === 'gamma_list' ? 'Gamma 列表兜底' : 'slug 直链'}`,
                            `${cfg.entrySideMode === 'trend_follow' ? '趋势跟单' : '随机方向'}: ${sideLabel} | 名义 stake: ${stakeTarget.toFixed(4)} USD | 参考价≈${entryPx.toFixed(4)} | 份额≈${assumedShares.toFixed(4)}`,
                            tokenId ? `tokenId: ${shortTokenId(tokenId)}` : 'tokenId: （空）',
                            `本序列档位: 第 ${s.stepIndex + 1} 档（内部 stepIndex=${s.stepIndex}）；与 [${skd}] 外其它键独立`,
                            martingaleBetRoundVerboseZh(s.stepIndex),
                            sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps),
                        ].join('\n')
                    );
                } else {
                    lines.push(
                        [
                            `◇ [${skd}] 跟踪下一时间段 | ${formatTheoryWindowRangeUtc(picked.windowStartSec, INTERVAL_SECONDS[interval])}`,
                            `✓ [${skd}] 模拟开仓 ${sideLabel} ${stakeTarget.toFixed(2)}U 入@${entryPx.toFixed(3)} 股≈${assumedShares.toFixed(2)}`,
                            `距收盘: ${rem} | ${martingaleBetRoundCompactZh(s.stepIndex)}`,
                            `${sessionPnlSummary(s.sessionRealizedPnlUsd, s.stepIndex, cfg.maxMartingaleSteps)}`,
                            purld,
                        ].join('\n')
                    );
                }
                fireMartingaleMail(() =>
                    notifyMartingaleOrderFilled(
                        {
                            seriesKey: skd,
                            execMode: 'dryrun',
                            sideLabel,
                            stakeUsd: stakeTarget,
                            entryPrice: entryPx,
                            shares: assumedShares,
                            slug: picked.slug,
                            question: mq,
                            conditionId: String(picked.market.conditionId || ''),
                            tokenId,
                            stepTierZh: martingaleBetRoundCompactZh(s.stepIndex),
                            sessionRealizedPnlUsd: s.sessionRealizedPnlUsd,
                            theoryWindowUtc: formatTheoryWindowRangeUtc(
                                picked.windowStartSec,
                                INTERVAL_SECONDS[interval]
                            ),
                        },
                        cfg.emailOnOrder
                    )
                );
            }
        }
    }
    saveMartingaleState(cfg.stateFilePath, state);
    const wantFast = settledAny || pollAccel.useFastPoll;
    let nextSleepSec = wantFast
        ? Math.min(defaultPollSec, cfg.pollIntervalNearCloseSec)
        : defaultPollSec;
    if (pollAccel.useUltraFastPoll) {
        nextSleepSec = Math.min(nextSleepSec, cfg.pollIntervalAfterExpiredSec);
    }
    return { lines, state, nextSleepSec, settledThisPass: settledAny };
};
