/**
 * @author li.mingfeng
 * Generated By AI Start (Cursor)
 * 马丁格尔策略：配置类型与从 `process.env` 解析（须先 `ensureMartingaleDotenv` 合并 `.env.martingale`）。
 * Generated By AI End (Cursor)
 */

import { ensureMartingaleDotenv } from './martingaleDotenv';

export type MartingaleAsset = 'BTC' | 'ETH' | 'SOL';

export type MartingaleIntervalKey = '5m' | '15m';

/** 新开仓选边：random=随机；trend_follow=仅当 CLOB/Gamma 显示偏高侧价≥阈值时押价高侧 */
export type MartingaleEntrySideMode = 'random' | 'trend_follow';

export const INTERVAL_SECONDS: Record<MartingaleIntervalKey, number> = {
    '5m': 300,
    '15m': 900,
};

export const ASSET_TO_SLUG_PREFIX: Record<MartingaleAsset, string> = {
    BTC: 'btc',
    ETH: 'eth',
    SOL: 'sol',
};

export type MartingaleRuntimeConfig = {
    enabled: boolean;
    liveEnabled: boolean;
    assets: MartingaleAsset[];
    intervals: MartingaleIntervalKey[];
    baseStakeUsd: number;
    maxMartingaleSteps: number;
    pollIntervalSec: number;
    stateFilePath: string;
    /**
     * 非空时：`npm run martingale-live` 使用该路径作为 state，dryrun/backtest 仍用 stateFilePath。
     * 用于与模拟盘隔离累计盈亏与马丁步数。
     */
    liveStateFilePath: string | null;
    excelReportPath: string;
    randomSeed: number | null;
    assumedEntryPrice: number;
    slugLookbackWindows: number;
    backtestDays: number;
    backtestRequestGapMs: number;
    gammaFallbackEnabled: boolean;
    gammaFallbackMaxPages: number;
    minOrderUsd: number;
    minRemainingSecToEnter: number;
    dryRunBaseStakeUsd: number | null;
    dryRunPollIntervalSec: number | null;
    /** 挂单未收盘时，至少隔多少秒打一条「等待结算」日志；0=每轮轮询都打 */
    waitingSettlementLogSec: number;
    /**
     * 单行「待收盘」心跳：至少隔多少秒打一条（带数字倒计时、倍投笔数）；0=每轮轮询都打。
     * 与 waitingSettlementLogSec 独立，详日志仍用后者节流。
     */
    pendingCountdownLogSec: number;
    /**
     * Gamma 已过期或已过理论窗时，紧凑「⏳ 待收盘」最小间隔（秒），避免 2s 轮询下同一状态刷屏。
     * 与 pendingCountdownLogSec 取 max；详日志仍用 waitingSettlementLogSec。
     */
    pendingExpiredHeartbeatMinSec: number;
    /** true：等待/跳过等日志输出多行详解；false：单行摘要（控制台更干净） */
    logVerbose: boolean;
    /**
     * true：本进程内每个资产+周期在**尚未完成首单**前，不追「已跑过久的当前 slug 窗」、不抢在理论窗起点前进场；
     * 并结合「slug 理论剩余」与 MARTINGALE_STARTUP_CURRENT_WINDOW_GRACE_SEC 约束首单时机。
     */
    startupWaitNextWindow: boolean;
    /**
     * 与 startupWaitNextWindow 配合：以 floor(now/周期)×周期 为当前理论窗起点，若已超出该起点这么多秒，
     * 则首单不允许再挂在「当前理论窗」上，须等 discover 指向下一段 windowStart（避免启动即追尾盘）。
     */
    startupCurrentWindowGraceSec: number;
    /**
     * 仅模拟盘入口：进程启动时删除 state 文件并清空 runner 内存锚点（各资产+周期从首笔重来）。
     */
    dryRunResetStateOnStart: boolean;
    /**
     * 理论窗口结束后再等这么多秒，若 Gamma 仍 closed=false 且 outcomePrices 可明确推断胜负，则强制结算（0=关闭）。
     */
    forceSettleGraceAfterWindowSec: number;
    /**
     * 理论窗结束后延迟这么多秒，若仍未 closed，则用 CLOB 两侧 midpoint/last 价**谁高谁赢**尝试结算（0=关闭本路径）。
     * 优先于 forceSettleGraceAfterWindowSec 的 Gamma 价推断（更早触发可更快挂下一窗）。
     */
    bookSettleAfterWindowSec: number;
    /**
     * CLOB 两侧价差小于该值则不采用订单簿推断（避免噪声；0=不检查价差，直接按价高者胜）。
     */
    bookSettleMinSpread: number;
    /** 距 Gamma endDate 不足该秒数（或已过期）时，本轮扫描后改用 pollIntervalNearCloseSec 休眠 */
    nearClosePollThresholdSec: number;
    /** 临收盘/待结算/刚结算后使用的更短轮询间隔（秒），会与常规轮询取 min */
    pollIntervalNearCloseSec: number;
    /**
     * Gamma endDate 已过期或已过本窗理论结束时，休眠再与上两项取 min（便于尽快等 closed / 强制推断结算后接下一窗）。
     */
    pollIntervalAfterExpiredSec: number;
    /** Gamma/列表 HTTP 单次超时（毫秒），独立于主项目 REQUEST_TIMEOUT_MS */
    httpTimeoutMs: number;
    /** Gamma/列表 HTTP 失败重试次数（每次请求内指数退避） */
    httpRetryLimit: number;
    /**
     * 成交通知邮件：需根目录 `.env` 已配置 EMAIL_NOTIFY_ENABLED 与 SMTP（与跟单共用）。
     * 下单成交后发送（live / dryrun 均可能触发）。
     */
    emailOnOrder: boolean;
    /**
     * 结算通知邮件：窗口收盘结算并写入 Excel 后发送，含本局盈亏与会话累计。
     */
    emailOnSettle: boolean;
    /**
     * 仅 martingale-live：每隔这么多分钟尝试一次链上 redeem（0=关闭）。
     * 与 npm run redeem-resolved 相同 Data API 条件（redeemable + 价贴近 0/1）。
     */
    redeemIntervalMinutes: number;
    /** 新开仓选边模式（dryrun/live 共用 runner 逻辑） */
    entrySideMode: MartingaleEntrySideMode;
    /**
     * trend_follow：偏高侧隐含价至少为该值才开仓（例如 0.7 表示 Down≥0.7 才跟 Down）。
     */
    trendFollowMinLeadingPrice: number;
    /**
     * 已解析；当前 trend_follow 以「首次穿越阈值」锁边，runner 未用价差过滤（保留键供后续扩展）。
     */
    trendFollowMinSpread: number;
};

const parseAssetList = (raw: string | undefined): MartingaleAsset[] => {
    const s = (raw || 'BTC,ETH,SOL').trim();
    const out: MartingaleAsset[] = [];
    for (const part of s.split(',')) {
        const u = part.trim().toUpperCase();
        if (u === 'BTC' || u === 'ETH' || u === 'SOL') {
            out.push(u);
        }
    }
    return out.length ? out : ['BTC', 'ETH', 'SOL'];
};

const parseIntervalList = (raw: string | undefined): MartingaleIntervalKey[] => {
    const s = (raw || '5m')
        .trim()
        .toLowerCase()
        .replace(/，/g, ',');
    const out: MartingaleIntervalKey[] = [];
    for (const part of s.split(',')) {
        const t = part.trim().toLowerCase().replace(/\s+/g, '');
        if (t === '5m' || t === '15m') {
            out.push(t);
        }
    }
    return out.length ? out : ['5m'];
};

const assertSingleIntervalOnly = (intervals: MartingaleIntervalKey[]): void => {
    if (intervals.length === 1) {
        return;
    }
    const joined = intervals.length ? intervals.join(', ') : '（未能解析出有效项）';
    throw new Error(
        'MARTINGALE_INTERVALS 仅允许填写一个周期：5m 或 15m（不支持在同一进程内同时跑 5 分钟与 15 分钟）。' +
            `当前解析得到 ${intervals.length} 项: ${joined}。请改为例如 MARTINGALE_INTERVALS=5m 或 MARTINGALE_INTERVALS=15m。`
    );
};

/**
 * 从环境变量组装运行时配置（键名与 `.env.martingale.example` 一致，中文说明见该文件）。
 * 依赖 `ensureMartingaleDotenv()`：已合并根目录 `.env` 与 `.env.martingale`。
 */
export const martingaleConfigFromEnv = (): MartingaleRuntimeConfig => {
    ensureMartingaleDotenv();
    const seedRaw = (process.env.MARTINGALE_RANDOM_SEED || '').trim();
    const seedParsed = seedRaw === '' ? NaN : parseInt(seedRaw, 10);
    const intervalsParsed = parseIntervalList(process.env.MARTINGALE_INTERVALS);
    assertSingleIntervalOnly(intervalsParsed);
    return {
        enabled: process.env.MARTINGALE_ENABLED === 'true',
        liveEnabled: process.env.MARTINGALE_LIVE_ENABLED === 'true',
        assets: parseAssetList(process.env.MARTINGALE_ASSETS),
        intervals: intervalsParsed,
        baseStakeUsd: Math.max(0.01, parseFloat(process.env.MARTINGALE_BASE_STAKE_USD || '1')),
        maxMartingaleSteps: Math.max(1, parseInt(process.env.MARTINGALE_MAX_STEPS || '4', 10)),
        pollIntervalSec: Math.max(3, parseInt(process.env.MARTINGALE_POLL_INTERVAL_SEC || '15', 10)),
        stateFilePath: (process.env.MARTINGALE_STATE_FILE || 'reports/martingale-state.json').trim(),
        liveStateFilePath: (() => {
            const s = (process.env.MARTINGALE_LIVE_STATE_FILE || '').trim();
            return s !== '' ? s : null;
        })(),
        excelReportPath: (process.env.MARTINGALE_EXCEL_PATH || 'reports/martingale-history.xlsx').trim(),
        randomSeed: Number.isFinite(seedParsed) ? seedParsed : null,
        assumedEntryPrice: Math.min(
            0.99,
            Math.max(0.01, parseFloat(process.env.MARTINGALE_ASSUMED_ENTRY_PRICE || '0.5'))
        ),
        slugLookbackWindows: Math.max(0, parseInt(process.env.MARTINGALE_SLUG_LOOKBACK_WINDOWS || '2', 10)),
        backtestDays: Math.max(1, parseInt(process.env.MARTINGALE_BACKTEST_DAYS || '7', 10)),
        backtestRequestGapMs: Math.max(0, parseInt(process.env.MARTINGALE_BACKTEST_REQUEST_GAP_MS || '120', 10)),
        gammaFallbackEnabled: process.env.MARTINGALE_GAMMA_FALLBACK_ENABLED !== 'false',
        gammaFallbackMaxPages: Math.max(1, parseInt(process.env.MARTINGALE_GAMMA_FALLBACK_MAX_PAGES || '15', 10)),
        minOrderUsd: Math.max(0.01, parseFloat(process.env.MARTINGALE_MIN_ORDER_USD || '1')),
        minRemainingSecToEnter: Math.max(
            0,
            parseInt(process.env.MARTINGALE_MIN_REMAINING_SEC_TO_ENTER || '120', 10)
        ),
        dryRunBaseStakeUsd: (() => {
            const s = (process.env.MARTINGALE_DRYRUN_BASE_STAKE_USD || '').trim();
            if (s === '') {
                return null;
            }
            const v = parseFloat(s);
            return Number.isFinite(v) && v > 0 ? v : null;
        })(),
        dryRunPollIntervalSec: (() => {
            const s = (process.env.MARTINGALE_DRYRUN_POLL_INTERVAL_SEC || '').trim();
            if (s === '') {
                return null;
            }
            const v = parseInt(s, 10);
            return Number.isFinite(v) && v >= 3 ? v : null;
        })(),
        waitingSettlementLogSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_WAITING_SETTLEMENT_LOG_SEC || '60', 10)
        ),
        pendingCountdownLogSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_PENDING_COUNTDOWN_LOG_SEC || '10', 10)
        ),
        // 见 martingaleRunner：过期状态下紧凑「⏳」最小间隔，与 POLL_AFTER_EXPIRED 解耦
        pendingExpiredHeartbeatMinSec: Math.min(
            120,
            Math.max(2, parseInt(process.env.MARTINGALE_PENDING_EXPIRED_HEARTBEAT_MIN_SEC || '5', 10))
        ),
        logVerbose: process.env.MARTINGALE_LOG_VERBOSE === 'true',
        startupWaitNextWindow: process.env.MARTINGALE_STARTUP_WAIT_NEXT_WINDOW === 'true',
        startupCurrentWindowGraceSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_STARTUP_CURRENT_WINDOW_GRACE_SEC || '120', 10)
        ),
        dryRunResetStateOnStart: process.env.MARTINGALE_DRYRUN_RESET_STATE_ON_START === 'true',
        forceSettleGraceAfterWindowSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_FORCE_SETTLE_GRACE_AFTER_WINDOW_SEC || '0', 10)
        ),
        bookSettleAfterWindowSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_BOOK_SETTLE_AFTER_WINDOW_SEC || '0', 10)
        ),
        bookSettleMinSpread: Math.max(
            0,
            parseFloat(process.env.MARTINGALE_BOOK_SETTLE_MIN_SPREAD || '0.03')
        ),
        nearClosePollThresholdSec: Math.max(
            0,
            parseInt(process.env.MARTINGALE_NEAR_CLOSE_POLL_THRESHOLD_SEC || '120', 10)
        ),
        pollIntervalNearCloseSec: Math.max(
            2,
            parseInt(process.env.MARTINGALE_POLL_INTERVAL_NEAR_CLOSE_SEC || '3', 10)
        ),
        pollIntervalAfterExpiredSec: Math.max(
            1,
            parseInt(process.env.MARTINGALE_POLL_INTERVAL_AFTER_EXPIRED_SEC || '2', 10)
        ),
        httpTimeoutMs: Math.max(
            5000,
            parseInt(process.env.MARTINGALE_HTTP_TIMEOUT_MS || '25000', 10)
        ),
        httpRetryLimit: Math.min(
            10,
            Math.max(1, parseInt(process.env.MARTINGALE_HTTP_RETRY_LIMIT || '5', 10))
        ),
        emailOnOrder: process.env.MARTINGALE_EMAIL_ON_ORDER === 'true',
        emailOnSettle: process.env.MARTINGALE_EMAIL_ON_SETTLE === 'true',
        redeemIntervalMinutes: Math.max(
            0,
            parseInt(process.env.MARTINGALE_REDEEM_INTERVAL_MINUTES || '0', 10)
        ),
        entrySideMode: (() => {
            const raw = (process.env.MARTINGALE_ENTRY_SIDE_MODE || 'random').trim().toLowerCase();
            return raw === 'trend_follow' || raw === 'trend-follow' ? 'trend_follow' : 'random';
        })(),
        trendFollowMinLeadingPrice: Math.min(
            0.99,
            Math.max(0.51, parseFloat(process.env.MARTINGALE_TREND_FOLLOW_MIN_LEADING_PRICE || '0.7'))
        ),
        trendFollowMinSpread: Math.max(
            0,
            parseFloat(process.env.MARTINGALE_TREND_FOLLOW_MIN_SPREAD || '0')
        ),
    };
};

export const seriesKey = (asset: MartingaleAsset, interval: MartingaleIntervalKey): string => {
    return `${asset}:${interval}`;
};

export type MartingaleHttpFetchOpts = {
    timeoutMs: number;
    retries: number;
};

export const martingaleHttpFetchOpts = (cfg: MartingaleRuntimeConfig): MartingaleHttpFetchOpts => {
    return { timeoutMs: cfg.httpTimeoutMs, retries: cfg.httpRetryLimit };
};
